
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class AddSiteform extends javax.swing.JFrame {
     Connection con = null;
       Connection conn = null;
   Statement stmt = null;
PreparedStatement pst = null;
ResultSet rs = null;
String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost/user";
        String uName ="root";
        String pwd = "root";
        String name;


    /**
     * Creates new form AddSiteform
     */
    public AddSiteform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addsiteSubmit = new javax.swing.JButton();
        siteLocationLabel = new javax.swing.JLabel();
        sitelocationfield = new javax.swing.JTextField();
        StartDateLabel = new javax.swing.JLabel();
        EndDatelabelsite = new javax.swing.JLabel();
        SiteNamelabel = new javax.swing.JLabel();
        sitenamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnbacklab = new javax.swing.JButton();
        siteenddate = new com.toedter.calendar.JDateChooser();
        sitestartdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addsiteSubmit.setText("Submit");
        addsiteSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsiteSubmitActionPerformed(evt);
            }
        });

        siteLocationLabel.setText("Location");

        sitelocationfield.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                sitelocationfieldInputMethodTextChanged(evt);
            }
        });

        StartDateLabel.setText("Start Date");

        EndDatelabelsite.setText("End Date");

        SiteNamelabel.setText("Site Name");

        sitenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitenamefieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Add New Site");

        btnbacklab.setText("Back");
        btnbacklab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacklabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnbacklab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addsiteSubmit)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SiteNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siteLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartDateLabel)
                    .addComponent(EndDatelabelsite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sitelocationfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sitenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siteenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sitestartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel)
                    .addComponent(sitenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteLocationLabel)
                    .addComponent(sitelocationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StartDateLabel)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EndDatelabelsite, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siteenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addsiteSubmit)
                            .addComponent(btnbacklab)))
                    .addComponent(sitestartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addsiteSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsiteSubmitActionPerformed
       
       
        try {
          
          
            conn = DriverManager.getConnection(url, uName, pwd);
            String sql = "INSERT INTO site"
            +"(SiteName, Location, StartDate, EndDate)"
            +"VALUES (?,?,?,?)";
          
            pst = conn.prepareStatement(sql);
            pst.setString(1, sitenamefield.getText());
            pst.setString(2, sitelocationfield.getText());
            pst.setString(3,((JTextField) sitestartdate.getDateEditor().getUiComponent()).getText());
             pst.setString(4,((JTextField) siteenddate.getDateEditor().getUiComponent()).getText());
            
           

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Site Added");
 
        } 
        catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_addsiteSubmitActionPerformed

    private void sitelocationfieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sitelocationfieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sitelocationfieldInputMethodTextChanged

    private void btnbacklabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacklabActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbacklabActionPerformed

    private void sitenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitenamefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSiteform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSiteform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSiteform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSiteform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSiteform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EndDatelabelsite;
    private javax.swing.JLabel SiteNamelabel;
    private javax.swing.JLabel StartDateLabel;
    private javax.swing.JButton addsiteSubmit;
    private javax.swing.JButton btnbacklab;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel siteLocationLabel;
    private com.toedter.calendar.JDateChooser siteenddate;
    private javax.swing.JTextField sitelocationfield;
    private javax.swing.JTextField sitenamefield;
    private com.toedter.calendar.JDateChooser sitestartdate;
    // End of variables declaration//GEN-END:variables
}
