
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author piyush veerbhan
 */
public class Cement extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
 int remaining=0;
 int count=0;
    /**
     * Creates new form Cement
     */
    public Cement() throws SQLException {
        initComponents();
        ShowCombo();
        showTableData();
    }
private void ShowCombo() throws SQLException{
    
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM site";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name=rs.getString("SiteName");
combosite.addItem(name);


}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cementfiledrec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cementtable = new javax.swing.JTable();
        SiteNamelabel5 = new javax.swing.JLabel();
        SiteNamelabel6 = new javax.swing.JLabel();
        cementdate = new com.toedter.calendar.JDateChooser();
        cementfiledrate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cementfiledvehicle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cementfiledsuppler = new javax.swing.JTextField();
        cementfiledbill = new javax.swing.JTextField();
        SiteNamelabel = new javax.swing.JLabel();
        cementbtnsubmit = new javax.swing.JButton();
        SiteNamelabel1 = new javax.swing.JLabel();
        cementbtnupdtae = new javax.swing.JButton();
        SiteNamelabel2 = new javax.swing.JLabel();
        cemenbtnck = new javax.swing.JButton();
        SiteNamelabel3 = new javax.swing.JLabel();
        cementfiledconsume = new javax.swing.JTextField();
        SiteNamelabel4 = new javax.swing.JLabel();
        btndel = new javax.swing.JButton();
        SiteNamelabel7 = new javax.swing.JLabel();
        combosite = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cementfiledrec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cementfiledrecKeyTyped(evt);
            }
        });

        cementtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Receive", "Consume", "Rate", "Vehicle No.", "Suppler Name", "Bill No.", "Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cementtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cementtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cementtable);

        SiteNamelabel5.setText(" Suppler Name");

        SiteNamelabel6.setText("Receipt No.");

        cementfiledrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cementfiledrateKeyTyped(evt);
            }
        });

        jLabel1.setText("Bags");

        jLabel2.setText("Bags");

        cementfiledbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cementfiledbillActionPerformed(evt);
            }
        });

        SiteNamelabel.setText("    Date");

        cementbtnsubmit.setText("Submit");
        cementbtnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cementbtnsubmitActionPerformed(evt);
            }
        });

        SiteNamelabel1.setText("   Receive");

        cementbtnupdtae.setText("Update");
        cementbtnupdtae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cementbtnupdtaeActionPerformed(evt);
            }
        });

        SiteNamelabel2.setText("   Rate");

        cemenbtnck.setText("Back");
        cemenbtnck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemenbtnckActionPerformed(evt);
            }
        });

        SiteNamelabel3.setText("  Vehicle No.");

        cementfiledconsume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cementfiledconsumeActionPerformed(evt);
            }
        });
        cementfiledconsume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cementfiledconsumeKeyTyped(evt);
            }
        });

        SiteNamelabel4.setText("  Consume");

        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        SiteNamelabel7.setText("Select Site Name");

        combosite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combositePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combosite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combositeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cemenbtnck)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cementbtnsubmit)
                        .addGap(11, 11, 11)
                        .addComponent(cementbtnupdtae)
                        .addGap(18, 18, 18)
                        .addComponent(btndel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SiteNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteNamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteNamelabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteNamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteNamelabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteNamelabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteNamelabel5))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cementfiledbill)
                                    .addComponent(cementfiledsuppler)
                                    .addComponent(cementfiledvehicle)
                                    .addComponent(cementfiledrate)
                                    .addComponent(cementfiledconsume)
                                    .addComponent(cementfiledrec, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(cementdate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SiteNamelabel7)
                        .addGap(28, 28, 28)
                        .addComponent(combosite, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combosite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SiteNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cementdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SiteNamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cementfiledrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cementfiledconsume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cementfiledrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cementfiledvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cementfiledsuppler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cementfiledbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cementbtnsubmit)
                    .addComponent(cementbtnupdtae)
                    .addComponent(btndel))
                .addGap(56, 56, 56)
                .addComponent(cemenbtnck)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cementfiledbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cementfiledbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cementfiledbillActionPerformed

    private void cemenbtnckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemenbtnckActionPerformed
        new Material().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cemenbtnckActionPerformed

    private void cementfiledconsumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cementfiledconsumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cementfiledconsumeActionPerformed
public void showTableData(){

 try{
    
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"cement";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
cementtable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
 JOptionPane.showMessageDialog(null,"Please Add A Site First");
 
}

 
}
    private void cementbtnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cementbtnsubmitActionPerformed
       try {
           if(((JTextField) cementdate.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
            }
            if(cementfiledrec.getText().length()==0||cementfiledconsume.getText().length()==0||cementfiledrate.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Any field from Receive,consume or rate is Empty");
            return;
            }
           
           
       int remain;
       remian();
       //System.out.println(remaining);
    remain=(Integer.parseInt(cementfiledrec.getText()))-(Integer.parseInt(cementfiledconsume.getText()))+remaining;
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"cement";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(Date, Receive, Consume, Rate, VehicleNo, SupplerName, Receipt, Remaining)"
+"VALUES (?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) cementdate.getDateEditor().getUiComponent()).getText());
pst.setString(2,cementfiledrec.getText());
pst.setString(3,cementfiledconsume.getText());
pst.setString(4,cementfiledrate.getText());
pst.setString(5,cementfiledvehicle.getText());
pst.setString(6,cementfiledsuppler.getText());
pst.setString(7,cementfiledbill.getText());
pst.setInt(8,remain);
pst.executeUpdate();
showTableData();
refresh();
return ;
}

} 

pst.executeUpdate("CREATE TABLE "+ tablename +
                "("+"Date TEXT(25),Receive INT(10),Consume INT(10),Rate FLOAT(10),VehicleNo VARCHAR(20),SupplerName TEXT(30),Receipt VARCHAR(25),Remaining INT(20))");
String sql = "INSERT INTO "+tablename
        +"(Date, Receive, Consume, Rate, VehicleNo, SupplerName, Receipt, Remaining)"
+"VALUES (?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) cementdate.getDateEditor().getUiComponent()).getText());
pst.setString(2,cementfiledrec.getText());
pst.setString(3,cementfiledconsume.getText());
pst.setString(4,cementfiledrate.getText());
pst.setString(5,cementfiledvehicle.getText());
pst.setString(6,cementfiledsuppler.getText());
pst.setString(7,cementfiledbill.getText());
pst.setInt(8,remain);
pst.executeUpdate();
showTableData();
refresh();


       
        
        
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cementbtnsubmitActionPerformed

    private void combositePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combositePopupMenuWillBecomeInvisible
       try{
    
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"cement";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equals(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
cementtable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}
    }//GEN-LAST:event_combositePopupMenuWillBecomeInvisible
private void refresh(){

//cementdate.setDateFormatString("");
cementfiledrec.setText("");
cementfiledconsume.setText("");
cementfiledrate.setText("");
cementfiledvehicle.setText("");
cementfiledsuppler.setText("");
cementfiledbill.setText("");



}
    private void cementtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cementtableMouseClicked
        int i=cementtable.getSelectedRow();
        TableModel model=cementtable.getModel();
        String date=model.getValueAt(i,0).toString();
        cementfiledrec.setText(model.getValueAt(i,1).toString());
        cementfiledconsume.setText(model.getValueAt(i,2).toString());
        cementfiledrate.setText(model.getValueAt(i,3).toString());
        cementfiledvehicle.setText(model.getValueAt(i,4).toString());
        cementfiledsuppler.setText(model.getValueAt(i,5).toString());
        cementfiledbill.setText(model.getValueAt(i,6).toString());
        ((JTextField) cementdate.getDateEditor().getUiComponent()).setText(date);
    }//GEN-LAST:event_cementtableMouseClicked

    private void cementbtnupdtaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cementbtnupdtaeActionPerformed
       try {
       int remain;
       remian();
       //System.out.println(remaining);
    remain=(Integer.parseInt(cementfiledrec.getText()))-(Integer.parseInt(cementfiledconsume.getText()))+remaining;
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"cement";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "UPDATE "+tablename
        +" SET Date=?, Receive=?, Consume=?, Rate=?, VehicleNo=?, SupplerName=?, Receipt=?, Remaining=? WHERE Date=?";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) cementdate.getDateEditor().getUiComponent()).getText());
pst.setString(2,cementfiledrec.getText());
pst.setString(3,cementfiledconsume.getText());
pst.setString(4,cementfiledrate.getText());
pst.setString(5,cementfiledvehicle.getText());
pst.setString(6,cementfiledsuppler.getText());
pst.setString(7,cementfiledbill.getText());
pst.setInt(8,remain);
pst.setString(9,((JTextField) cementdate.getDateEditor().getUiComponent()).getText());
pst.executeUpdate();
showTableData();
refresh();
return ;
}

}      
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cementbtnupdtaeActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
try {
       int remain;
       remian();
       //System.out.println(remaining);
    remain=(Integer.parseInt(cementfiledrec.getText()))-(Integer.parseInt(cementfiledconsume.getText()))+remaining;
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"cement";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename
        +" WHERE Date=?";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) cementdate.getDateEditor().getUiComponent()).getText());
pst.executeUpdate();
showTableData();
refresh();
return ;
}

}      
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }//GEN-LAST:event_btndelActionPerformed

    private void cementfiledrecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cementfiledrecKeyTyped
         char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_cementfiledrecKeyTyped

    private void cementfiledconsumeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cementfiledconsumeKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_cementfiledconsumeKeyTyped

    private void cementfiledrateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cementfiledrateKeyTyped
  char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
JOptionPane.showMessageDialog(null,"Two Decimals are not allow");} // TODO add your handling code here:
    }//GEN-LAST:event_cementfiledrateKeyTyped

    private void combositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combositeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combositeActionPerformed
private void remian(){
try{
   if(combosite.getSelectedItem()!=null){
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"cement";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT Remaining FROM "+tablename+" ORDER BY Remaining DESC LIMIT 1";
    //System.out.println(sql);
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
remaining=rs.getInt(1);
//System.out.println(remaining);
}}}
   else{
   return;
   }

}
catch(Exception ex){
    remaining=0;
//JOptionPane.showMessageDialog(null, ex);
 
}


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cement().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Cement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SiteNamelabel;
    private javax.swing.JLabel SiteNamelabel1;
    private javax.swing.JLabel SiteNamelabel2;
    private javax.swing.JLabel SiteNamelabel3;
    private javax.swing.JLabel SiteNamelabel4;
    private javax.swing.JLabel SiteNamelabel5;
    private javax.swing.JLabel SiteNamelabel6;
    private javax.swing.JLabel SiteNamelabel7;
    private javax.swing.JButton btndel;
    private javax.swing.JButton cemenbtnck;
    private javax.swing.JButton cementbtnsubmit;
    private javax.swing.JButton cementbtnupdtae;
    private com.toedter.calendar.JDateChooser cementdate;
    private javax.swing.JTextField cementfiledbill;
    private javax.swing.JTextField cementfiledconsume;
    private javax.swing.JTextField cementfiledrate;
    private javax.swing.JTextField cementfiledrec;
    private javax.swing.JTextField cementfiledsuppler;
    private javax.swing.JTextField cementfiledvehicle;
    private javax.swing.JTable cementtable;
    private javax.swing.JComboBox combosite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
