
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class EartingForm extends javax.swing.JFrame {
    Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
showTable st=new showTable();
int count=0;

float totalAux;
float totalEarthpit;

float GrandTotal;
float total;
int id;
    
    
    
      void total(){
    
     totalAux=Float.parseFloat(AuxiliryField.getText())*Float.parseFloat(AuxiliryRateField.getText());
    
      totalEarthpit=Float.parseFloat(EarthPitField.getText())*Float.parseFloat(EarthRateFiled.getText());
    
     
     
     AuxiliryRateField2.setText(""+totalAux);
     EarthRateFiled2.setText(""+totalEarthpit);
     GrandTotal=Float.parseFloat(ExcavationFieldEarthing.getText())+Float.parseFloat(EarthMateField.getText())+totalAux+totalEarthpit;
    
         
    }

    /**
     * Creates new form EartingForm
     */
    public EartingForm() {
        initComponents();
         st.ShowdropDown(AddSite);
        st.showTableData(EarthTable, AddSite, "earthing");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ExcavationFieldEarthing = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EarthMateField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AuxiliryField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EarthPitField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EarthTable = new javax.swing.JTable();
        AuxiliryRateField = new javax.swing.JTextField();
        EarthRateFiled = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        otherUpdateButton = new javax.swing.JButton();
        OtherdelButton = new javax.swing.JButton();
        OtherBackButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dateOther = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        AddSite = new javax.swing.JComboBox<>();
        AuxiliryRateField1 = new javax.swing.JTextField();
        EarthRateFiled1 = new javax.swing.JTextField();
        AuxiliryRateField2 = new javax.swing.JTextField();
        EarthRateFiled2 = new javax.swing.JTextField();
        AuxiliryRateField3 = new javax.swing.JTextField();
        EarthRateFiled3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Excavation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        ExcavationFieldEarthing.setText("0");
        ExcavationFieldEarthing.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExcavationFieldEarthingFocusLost(evt);
            }
        });
        ExcavationFieldEarthing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ExcavationFieldEarthingKeyTyped(evt);
            }
        });
        getContentPane().add(ExcavationFieldEarthing, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 60, -1));

        jLabel2.setText("Earth Mate");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        EarthMateField.setText("0");
        EarthMateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EarthMateFieldFocusLost(evt);
            }
        });
        EarthMateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EarthMateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(EarthMateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 60, -1));

        jLabel3.setText("Auxiliry");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        AuxiliryField.setText("0");
        AuxiliryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AuxiliryFieldFocusLost(evt);
            }
        });
        AuxiliryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AuxiliryFieldKeyTyped(evt);
            }
        });
        getContentPane().add(AuxiliryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 60, -1));

        jLabel4.setText("Earth Pit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        EarthPitField.setText("0");
        EarthPitField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EarthPitFieldFocusLost(evt);
            }
        });
        EarthPitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarthPitFieldActionPerformed(evt);
            }
        });
        EarthPitField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EarthPitFieldKeyTyped(evt);
            }
        });
        getContentPane().add(EarthPitField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 60, -1));

        jLabel5.setText("Earting Form");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 10, 77, -1));

        EarthTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Excavation", "EarthMate", "Auxiliry", "EarthPit", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        EarthTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EarthTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EarthTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 573, -1));

        AuxiliryRateField.setText("0");
        AuxiliryRateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AuxiliryRateFieldFocusLost(evt);
            }
        });
        AuxiliryRateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AuxiliryRateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(AuxiliryRateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 60, -1));

        EarthRateFiled.setText("0");
        EarthRateFiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EarthRateFiledFocusLost(evt);
            }
        });
        EarthRateFiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EarthRateFiledKeyTyped(evt);
            }
        });
        getContentPane().add(EarthRateFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 59, -1));

        jLabel6.setText("Rate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        otherUpdateButton.setText("Update");
        otherUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(otherUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        OtherdelButton.setText("Delete");
        OtherdelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherdelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OtherdelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 67, -1));

        OtherBackButton.setText("Back");
        OtherBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OtherBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 65, -1));

        jLabel7.setText("date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));
        getContentPane().add(dateOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel10.setText("Select Site");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        AddSite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                AddSitePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(AddSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));
        getContentPane().add(AuxiliryRateField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 60, -1));
        getContentPane().add(EarthRateFiled1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 59, -1));

        AuxiliryRateField2.setText("0");
        AuxiliryRateField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuxiliryRateField2ActionPerformed(evt);
            }
        });
        getContentPane().add(AuxiliryRateField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 60, -1));

        EarthRateFiled2.setText("0");
        getContentPane().add(EarthRateFiled2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 59, -1));
        getContentPane().add(AuxiliryRateField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 60, -1));
        getContentPane().add(EarthRateFiled3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 59, -1));

        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try {
            if(((JTextField) dateOther.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
                    }
               total();
                     remian();

                     float New_total=total+GrandTotal;

       
        String name=AddSite.getSelectedItem().toString();
        
        String tablename=name+"earthing";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(Date,Excavation, EarthMate, Auxiliary, EarthPit ,TotalAmount)"
+"VALUES (?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateOther.getDateEditor().getUiComponent()).getText());
pst.setString(2,ExcavationFieldEarthing.getText());
pst.setString(3,EarthMateField.getText());
pst.setString(4,AuxiliryRateField2.getText());
pst.setString(5,EarthRateFiled2.getText());
pst.setFloat(6,New_total);



pst.executeUpdate();
st.showTableData(EarthTable, AddSite, "earthing");
refresh();
return ;
}

} 
  //System.out.println("chal bc");
String sql1="CREATE TABLE "+ tablename +
                "("+"ID INT NOT NULL AUTO_INCREMENT, Date TEXT(20),Excavation FLOAT(25),EarthMate FLOAT(25),Auxiliary FLOAT(10),EarthPit FLOAT(15),"
        + "TotalAmount FLOAT(30),PRIMARY KEY(ID))";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql1);
//System.out.println(sql1);
pst.executeUpdate(sql1);


System.out.println("chal bc");
String sql = "INSERT INTO "+tablename
        +"(Date,Excavation, EarthMate, Auxiliary, EarthPit ,TotalAmount)"
+"VALUES (?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateOther.getDateEditor().getUiComponent()).getText());
pst.setString(2,ExcavationFieldEarthing.getText());
pst.setString(3,EarthMateField.getText());
pst.setString(4,AuxiliryRateField2.getText());
pst.setString(5,EarthRateFiled2.getText());
pst.setFloat(6,New_total);

pst.executeUpdate();
st.showTableData(EarthTable, AddSite, "earthing");
refresh();



       
        
        
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void OtherdelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherdelButtonActionPerformed
        try {
         if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
         }
        String name=AddSite.getSelectedItem().toString();
        String tablename=name+"earthing";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename+" WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
            pst.setInt(1,id);
            pst.executeUpdate();
            st.showTableData(EarthTable, AddSite, "earthing");
            JOptionPane.showMessageDialog(null, "delete successfully");

            refresh();

            return ;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    }
    }//GEN-LAST:event_OtherdelButtonActionPerformed

    private void EarthPitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarthPitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EarthPitFieldActionPerformed

    private void otherUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherUpdateButtonActionPerformed
        total();
        try {

            String name = AddSite.getSelectedItem().toString();
            String tablename = name+"earthing";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user", "root", "root");

            rs = con.getMetaData().getTables(null, null, null, null);
            while (rs.next()) {
                String check = rs.getString("Table_Name");
                if (check != null && check.equalsIgnoreCase(tablename)) {
                    String sql = "UPDATE "+tablename+" SET Date=?,Excavation=?, EarthMate=?, Auxiliary=?, EarthPit=? ,TotalAmount=? WHERE Date=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost/user", "root", "root");
                    //System.out.println(sql);
                    pst = con.prepareStatement(sql);
                    
                   pst.setString(1,((JTextField) dateOther.getDateEditor().getUiComponent()).getText());
pst.setString(2,ExcavationFieldEarthing.getText());
pst.setString(3,EarthMateField.getText());
pst.setString(4,AuxiliryRateField2.getText());
pst.setString(5,EarthRateFiled2.getText());
pst.setFloat(6,GrandTotal);


                    pst.setString(7, ((JTextField) dateOther.getDateEditor().getUiComponent()).getText());

                    pst.executeUpdate();
                    st.showTableData(EarthTable, AddSite, "earthing");
                    refresh();
                    return;
                }

            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_otherUpdateButtonActionPerformed

    private void AddSitePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_AddSitePopupMenuWillBecomeInvisible
        st.FillTableUSingcombo(AddSite, EarthTable, "earthing");

    }//GEN-LAST:event_AddSitePopupMenuWillBecomeInvisible

    private void EarthTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EarthTableMouseClicked
         int i = EarthTable.getSelectedRow();
        TableModel model = EarthTable.getModel();
       
        id=Integer.parseInt(model.getValueAt(i, 0).toString());
        String date = model.getValueAt(i, 1).toString();
        ((JTextField) dateOther.getDateEditor().getUiComponent()).setText(date);
        ExcavationFieldEarthing.setText(model.getValueAt(i,2).toString());
        EarthMateField.setText(model.getValueAt(i,3).toString());
        
        
                                    
    }//GEN-LAST:event_EarthTableMouseClicked

    private void OtherBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherBackButtonActionPerformed
        new WorkDone().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OtherBackButtonActionPerformed

    private void ExcavationFieldEarthingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExcavationFieldEarthingKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_ExcavationFieldEarthingKeyTyped

    private void EarthMateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EarthMateFieldKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_EarthMateFieldKeyTyped

    private void AuxiliryFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AuxiliryFieldKeyTyped
        char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_AuxiliryFieldKeyTyped

    private void AuxiliryRateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AuxiliryRateFieldKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_AuxiliryRateFieldKeyTyped

    private void EarthPitFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EarthPitFieldKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_EarthPitFieldKeyTyped

    private void EarthRateFiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EarthRateFiledKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_EarthRateFiledKeyTyped

    private void ExcavationFieldEarthingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExcavationFieldEarthingFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_ExcavationFieldEarthingFocusLost

    private void EarthMateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EarthMateFieldFocusLost
    count=0;      // TODO add your handling code here:
    }//GEN-LAST:event_EarthMateFieldFocusLost

    private void AuxiliryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AuxiliryFieldFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_AuxiliryFieldFocusLost

    private void AuxiliryRateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AuxiliryRateFieldFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_AuxiliryRateFieldFocusLost

    private void EarthPitFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EarthPitFieldFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_EarthPitFieldFocusLost

    private void EarthRateFiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EarthRateFiledFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_EarthRateFiledFocusLost

    private void AuxiliryRateField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuxiliryRateField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuxiliryRateField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EartingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EartingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EartingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EartingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EartingForm().setVisible(true);
            }
        });
    }
    
      private void remian(){
try{
   if(AddSite.getSelectedItem()!=null){
        String name=AddSite.getSelectedItem().toString();
        String tablename=name+"earthing";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT Totalamount FROM "+tablename+" ORDER BY ID DESC LIMIT 1";
    System.out.println(sql);
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
total=rs.getInt(1);
 System.out.println(total);
//System.out.println(remaining);
}}}
   else{
   return;
   }

}
catch(Exception ex){
    System.out.println("mai chal tha");
    total=0;
//JOptionPane.showMessageDialog(null, ex);
 
}


}
       private void refresh(){
         ExcavationFieldEarthing.setText("0");
    EarthRateFiled3.setText("0");
 
 EarthRateFiled1.setText("0");
 
 EarthMateField.setText("0");
 
 AuxiliryRateField3.setText("0");
 AuxiliryRateField2.setText("0");

AuxiliryRateField1.setText("0");

AuxiliryField.setText("0");
EarthPitField.setText("0");

      //dateOther.setDateFormatString("");
                
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AddSite;
    private javax.swing.JTextField AuxiliryField;
    private javax.swing.JTextField AuxiliryRateField;
    private javax.swing.JTextField AuxiliryRateField1;
    private javax.swing.JTextField AuxiliryRateField2;
    private javax.swing.JTextField AuxiliryRateField3;
    private javax.swing.JTextField EarthMateField;
    private javax.swing.JTextField EarthPitField;
    private javax.swing.JTextField EarthRateFiled;
    private javax.swing.JTextField EarthRateFiled1;
    private javax.swing.JTextField EarthRateFiled2;
    private javax.swing.JTextField EarthRateFiled3;
    private javax.swing.JTable EarthTable;
    private javax.swing.JTextField ExcavationFieldEarthing;
    private javax.swing.JButton OtherBackButton;
    private javax.swing.JButton OtherdelButton;
    private javax.swing.JButton SubmitButton;
    private com.toedter.calendar.JDateChooser dateOther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton otherUpdateButton;
    // End of variables declaration//GEN-END:variables
}
