
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author piyush veerbhan
 */
public class EmpDailyrep extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
ResultSet rs1=null;
ResultSet rs2=null;
int num=0;
String attendance;

    /**
     * Creates new form EmpDailyrep
     */
    public EmpDailyrep()throws SQLException {
        initComponents();
        ShowdropDown();
        ShowdropDown2();
        showTableData();
        
    }
public void ShowdropDown(){
    try{
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM site";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name=rs.getString("SiteName");
combosite.addItem(name);
}}
catch(Exception ex){
     JOptionPane.showMessageDialog(null,"Please Add A Site Firs or Employee");
        }
}
 
public void ShowdropDown2(){
     try{ String name=combosite.getSelectedItem().toString();
      String tablename=name+"empolyee";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM "+tablename+"";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name1=rs.getString("name");
    
comboempname.addItem(name1);
}}
catch(Exception ex){
 JOptionPane.showMessageDialog(null,"Please Add A Site First or Employee");}
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        empdailytable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empdailtbtnsubmit = new javax.swing.JButton();
        btnbck = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        combosite = new javax.swing.JComboBox();
        comboempname = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        present = new javax.swing.JRadioButton();
        absent = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        dateempdaily = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        totalattfiled = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalprefiled = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        totalabsfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empdailytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Attendance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empdailytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empdailytableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(empdailytable);

        jLabel1.setText("Select Site Name");

        jLabel2.setText("Select Empoyee Name");

        empdailtbtnsubmit.setText("Submit");
        empdailtbtnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empdailtbtnsubmitActionPerformed(evt);
            }
        });

        btnbck.setText("Back");
        btnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbckActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        combosite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combositePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        comboempname.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboempnamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel3.setText("Attendance");

        buttonGroup1.add(present);
        present.setText("Present");
        present.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentActionPerformed(evt);
            }
        });

        buttonGroup1.add(absent);
        absent.setText("Absent");
        absent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absentActionPerformed(evt);
            }
        });

        jLabel4.setText("Date");

        jLabel5.setText("Total Attendance");

        jLabel6.setText("Total Present");

        jLabel7.setText("Total Absent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbck)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empdailtbtnsubmit)
                                .addGap(32, 32, 32)
                                .addComponent(btnupdate)
                                .addGap(63, 63, 63)
                                .addComponent(btndel))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(absent)
                            .addComponent(present)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateempdaily, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboempname, 0, 112, Short.MAX_VALUE)
                                    .addComponent(combosite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(totalattfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(totalprefiled, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(totalabsfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(combosite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboempname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dateempdaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(present)
                                .addGap(18, 18, 18)
                                .addComponent(absent))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empdailtbtnsubmit)
                    .addComponent(btnupdate)
                    .addComponent(btndel))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalattfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(totalprefiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(totalabsfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnbck)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbckActionPerformed
        try {
            new Employee().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EmpDailyrep.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setVisible(false);
    }//GEN-LAST:event_btnbckActionPerformed

    private void absentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absentActionPerformed

    private void combositePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combositePopupMenuWillBecomeInvisible
        try {
            comboempname.removeAllItems();
        
            String name=combosite.getSelectedItem().toString();
      String tablename=name+"empolyee";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM "+tablename+"";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name1=rs.getString("name");
    
comboempname.addItem(name1);
}
        } catch (Exception e) { 
        }
    }//GEN-LAST:event_combositePopupMenuWillBecomeInvisible

    private void empdailtbtnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empdailtbtnsubmitActionPerformed
         try {
             if(((JTextField) dateempdaily.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
            }
             if(present.isSelected()!=true&&absent.isSelected()!=true){
             JOptionPane.showMessageDialog(null, "attendance is not selected");
             return;
             }
           if(present.isSelected()){
           attendance="Present";
           }
           else{
           attendance="Absent";
           }
            String name=comboempname.getSelectedItem().toString();
            String tablename=name+"attendance";
            
             con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
   
 String sql = "INSERT INTO "+tablename
            +"(Date, Attendance)"
            +"VALUES (?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
             pst.setString(1,((JTextField) dateempdaily.getDateEditor().getUiComponent()).getText());
            pst.setString(2,attendance);
           
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "inserted successfully");
showTableData();
attendacecal();
present();
absent();
//refresh();
return ;
}

} 
 String sql1="CREATE TABLE "+tablename+"("+"Date TEXT(100),Attendance TEXT(100))";
 //System.out.println(sql1);
 pst.executeUpdate(sql1);
String sql = "INSERT INTO "+tablename
            +"(Date, Attendance)"
            +"VALUES (?,?)";
  con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
  pst = con.prepareStatement(sql);
  pst.setString(1,((JTextField) dateempdaily.getDateEditor().getUiComponent()).getText());
  pst.setString(2,attendance);
  pst.executeUpdate();
showTableData();
attendacecal();
present();
absent();
//refresh();

        } catch (Exception e) {
              Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_empdailtbtnsubmitActionPerformed

    private void attendacecal(){
    
    try{
    
        String name=comboempname.getSelectedItem().toString();
        String tablename=name+"attendance";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT COUNT(*) FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
totalattfiled.setText(""+rs.getInt(1));

}}}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}
}
    private void present (){
    
     try{
    
        String name=comboempname.getSelectedItem().toString();
        String tablename=name+"attendance";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename+" WHERE Attendance LIKE 'P%'";
    //System.out.println(sql);
pst = con.prepareStatement(sql);
rs1=pst.executeQuery();




}}num=0;
while(rs1.next()){
num++;
        }
     totalprefiled.setText(""+num);}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}
    
    
    }
    private void absent(){
     try{
    
        String name=comboempname.getSelectedItem().toString();
        String tablename=name+"attendance";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename+" WHERE Attendance LIKE 'A%'";
    //System.out.println(sql);
pst = con.prepareStatement(sql);
rs1=pst.executeQuery();




}}num=0;
while(rs1.next()){
num++;
        }
     totalabsfield.setText(""+num);}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}
  
    
    
    }
    private void comboempnamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboempnamePopupMenuWillBecomeInvisible
try{
    
        String name=comboempname.getSelectedItem().toString();
        String tablename=name+"attendance";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
empdailytable.setModel(DbUtils.resultSetToTableModel(rs));
attendacecal();
present();
absent();

}}}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}        // TODO add your handling code here:
         // TODO add your handling code here:
    }//GEN-LAST:event_comboempnamePopupMenuWillBecomeInvisible

    private void empdailytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empdailytableMouseClicked
      int i=empdailytable.getSelectedRow();
        TableModel model=empdailytable.getModel();
        String date=model.getValueAt(i,0).toString();
       String attend=model.getValueAt(i,1).toString();
       if(attend.equals("Present")){
          present.setSelected(true);
      }else{
       
       absent.setSelected(true);
       }
       
        ((JTextField) dateempdaily.getDateEditor().getUiComponent()).setText(date);
    }//GEN-LAST:event_empdailytableMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
           if(present.isSelected()){
           attendance="Present";
           }
           else{
           attendance="Absent";
           }
            String name=comboempname.getSelectedItem().toString();
            String tablename=name+"attendance";
            
             con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
   
 String sql = "UPDATE "+tablename
            +" SET Date=?, Attendance=? WHERE Date=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
             pst.setString(1,((JTextField) dateempdaily.getDateEditor().getUiComponent()).getText());
            pst.setString(2,attendance);
           pst.setString(3,((JTextField) dateempdaily.getDateEditor().getUiComponent()).getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "UPDATED successfully");
showTableData();
attendacecal();
present();
absent();
//refresh();
return ;
}

} 
 

        } catch (Exception e) {
              Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        try {
           
            String name=comboempname.getSelectedItem().toString();
            String tablename=name+"attendance";
            
             con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
   
 String sql = "DELETE FROM "+tablename+" WHERE Date=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
             pst.setString(1,((JTextField) dateempdaily.getDateEditor().getUiComponent()).getText());
         
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "DELETE successfully");
showTableData();
attendacecal();
present();
absent();
//refresh();
return ;
}

} 
 

        } catch (Exception e) {
              Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void presentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentActionPerformed
public void showTableData(){

 try{
    
        String name=comboempname.getSelectedItem().toString();
        String tablename=name+"attendance";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
empdailytable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
 JOptionPane.showMessageDialog(null,"Please Add A Site First or Employee");
 
}

 
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpDailyrep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpDailyrep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpDailyrep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpDailyrep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmpDailyrep().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EmpDailyrep.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton absent;
    private javax.swing.JButton btnbck;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox comboempname;
    private javax.swing.JComboBox combosite;
    private com.toedter.calendar.JDateChooser dateempdaily;
    private javax.swing.JButton empdailtbtnsubmit;
    private javax.swing.JTable empdailytable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton present;
    private javax.swing.JTextField totalabsfield;
    private javax.swing.JTextField totalattfiled;
    private javax.swing.JTextField totalprefiled;
    // End of variables declaration//GEN-END:variables
}
