
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author piyush veerbhan
 */
public class Gitti extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
 float remaining=0;
 int count=0;
   
    public Gitti() throws SQLException {
        initComponents();
        ShowCombo();
        showTableData();
    }
private void ShowCombo() throws SQLException{
    
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM site";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name=rs.getString("SiteName");
combosite.addItem(name);


}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gittirecfiled = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Gittitable = new javax.swing.JTable();
        SiteNamelabel5 = new javax.swing.JLabel();
        SiteNamelabel6 = new javax.swing.JLabel();
        dategitti = new com.toedter.calendar.JDateChooser();
        gittisizefiled = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gittiratefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gittivehiclefiled = new javax.swing.JTextField();
        gittisupplfiled = new javax.swing.JTextField();
        SiteNamelabel = new javax.swing.JLabel();
        gittibtnsubmit = new javax.swing.JButton();
        SiteNamelabel1 = new javax.swing.JLabel();
        gittibtnupdate = new javax.swing.JButton();
        SiteNamelabel2 = new javax.swing.JLabel();
        gittibtnbck = new javax.swing.JButton();
        SiteNamelabel3 = new javax.swing.JLabel();
        gitticonfiled = new javax.swing.JTextField();
        SiteNamelabel4 = new javax.swing.JLabel();
        SiteNamelabel7 = new javax.swing.JLabel();
        gittibillfield = new javax.swing.JTextField();
        btndel = new javax.swing.JButton();
        SiteNamelabel8 = new javax.swing.JLabel();
        combosite = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gittirecfiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gittirecfiledFocusLost(evt);
            }
        });
        gittirecfiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gittirecfiledKeyTyped(evt);
            }
        });

        Gittitable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Receive", "Consume", "Size", "Rate", "Suppler Name", "Bill No.", "Vehicle No.", "Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Gittitable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GittitableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Gittitable);

        SiteNamelabel5.setText(" Vehicle No.");

        SiteNamelabel6.setText("Suppler Name");

        gittisizefiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gittisizefiledFocusLost(evt);
            }
        });
        gittisizefiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gittisizefiledKeyTyped(evt);
            }
        });

        jLabel1.setText("cm^3");

        gittiratefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gittiratefieldFocusLost(evt);
            }
        });
        gittiratefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gittiratefieldKeyTyped(evt);
            }
        });

        jLabel2.setText("cm^3");

        gittisupplfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gittisupplfiledActionPerformed(evt);
            }
        });

        SiteNamelabel.setText("    Date");

        gittibtnsubmit.setText("Submit");
        gittibtnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gittibtnsubmitActionPerformed(evt);
            }
        });

        SiteNamelabel1.setText("   Receive");

        gittibtnupdate.setText("Update");
        gittibtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gittibtnupdateActionPerformed(evt);
            }
        });

        SiteNamelabel2.setText("  Size");

        gittibtnbck.setText("Back");
        gittibtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gittibtnbckActionPerformed(evt);
            }
        });

        SiteNamelabel3.setText("  Rate");

        gitticonfiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gitticonfiledFocusLost(evt);
            }
        });
        gitticonfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gitticonfiledActionPerformed(evt);
            }
        });
        gitticonfiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gitticonfiledKeyTyped(evt);
            }
        });

        SiteNamelabel4.setText("  Consume");

        SiteNamelabel7.setText("Receipt No");

        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        SiteNamelabel8.setText("Select Site Name");

        combosite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combositePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gittibtnbck)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(gittibtnsubmit)
                            .addGap(18, 18, 18)
                            .addComponent(gittibtnupdate)
                            .addGap(18, 18, 18)
                            .addComponent(btndel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SiteNamelabel8)
                                .addGap(18, 18, 18)
                                .addComponent(combosite, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SiteNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SiteNamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SiteNamelabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SiteNamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SiteNamelabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SiteNamelabel5)
                                    .addComponent(SiteNamelabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SiteNamelabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dategitti, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(gittibillfield, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gittisupplfiled, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gittivehiclefiled, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gittiratefield, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gittisizefiled, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gitticonfiled, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gittirecfiled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combosite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SiteNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dategitti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SiteNamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gittirecfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gitticonfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gittisizefiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gittiratefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gittivehiclefiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNamelabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gittisupplfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gittibillfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteNamelabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gittibtnsubmit)
                    .addComponent(gittibtnupdate)
                    .addComponent(btndel))
                .addGap(40, 40, 40)
                .addComponent(gittibtnbck)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gittisupplfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gittisupplfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gittisupplfiledActionPerformed

    private void gittibtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gittibtnbckActionPerformed
        new Material().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gittibtnbckActionPerformed

    private void gitticonfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gitticonfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gitticonfiledActionPerformed

    private void gittibtnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gittibtnsubmitActionPerformed
       try {
           if(((JTextField) dategitti.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
            }
            if(gittirecfiled.getText().length()==0||gitticonfiled.getText().length()==0||gittiratefield.getText().length()==0||gittisizefiled.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Any field from Receive,consume,size or rate is Empty");
            return;
            }
           
           
       float remain;
       remian();
       //System.out.println(remaining);
    remain=(Float.parseFloat(gittirecfiled.getText()))-(Float.parseFloat(gitticonfiled.getText()))+remaining;
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"gitti";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(Date, Receive, Consume, Size, Rate, VehicleNo, SupplerName, Receipt, Remaining)"
+"VALUES (?,?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dategitti.getDateEditor().getUiComponent()).getText());
pst.setString(2,gittirecfiled.getText());
pst.setString(3,gitticonfiled.getText());
pst.setString(4,gittisizefiled.getText());
pst.setString(5,gittiratefield.getText());
pst.setString(6,gittivehiclefiled.getText());
pst.setString(7,gittisupplfiled.getText());
pst.setString(8,gittibillfield.getText());
pst.setFloat(9,remain);
pst.executeUpdate();
showTableData();
refresh();
return ;
}

} 

pst.executeUpdate("CREATE TABLE "+ tablename +
                "("+"Date TEXT(25),Receive FLOAT(10),Consume FLOAT(10),Size FLOAT(20),Rate FLOAT(10),VehicleNo VARCHAR(20),SupplerName TEXT(30),Receipt VARCHAR(25),Remaining FLOAT(20))");
String sql = "INSERT INTO "+tablename
        +"(Date, Receive, Consume, size, Rate, VehicleNo, SupplerName, Receipt, Remaining)"
+"VALUES (?,?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dategitti.getDateEditor().getUiComponent()).getText());
pst.setString(2,gittirecfiled.getText());
pst.setString(3,gitticonfiled.getText());
pst.setString(4,gittisizefiled.getText());
pst.setString(5,gittiratefield.getText());
pst.setString(6,gittivehiclefiled.getText());
pst.setString(7,gittisupplfiled.getText());
pst.setString(8,gittibillfield.getText());
pst.setFloat(9,remain);
pst.executeUpdate();
showTableData();
refresh();


       
        
        
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_gittibtnsubmitActionPerformed

    private void combositePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combositePopupMenuWillBecomeInvisible
        try{
    
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"gitti";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
Gittitable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}
    }//GEN-LAST:event_combositePopupMenuWillBecomeInvisible

    private void refresh(){
   // dategitti.setDateFormatString("");
    gittirecfiled.setText("");
    gitticonfiled.setText("");
    gittisizefiled.setText("");
    gittiratefield.setText("");
    gittivehiclefiled.setText("");
    gittisupplfiled.setText("");
    gittibillfield.setText("");
    
  }
    private void GittitableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GittitableMouseClicked
       int i=Gittitable.getSelectedRow();
        TableModel model=Gittitable.getModel();
        String date=model.getValueAt(i,0).toString();
        gittirecfiled.setText(model.getValueAt(i,1).toString());
        gitticonfiled.setText(model.getValueAt(i,2).toString());
        gittisizefiled.setText(model.getValueAt(i,3).toString());
        gittiratefield.setText(model.getValueAt(i,4).toString());
        gittivehiclefiled.setText(model.getValueAt(i,5).toString());
        gittisupplfiled.setText(model.getValueAt(i,6).toString());
        gittibillfield.setText(model.getValueAt(i,7).toString());
        ((JTextField) dategitti.getDateEditor().getUiComponent()).setText(date);
    }//GEN-LAST:event_GittitableMouseClicked

    private void gittibtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gittibtnupdateActionPerformed
        try {
       float remain;
       remian();
       //System.out.println(remaining);
    remain=(Float.parseFloat(gittirecfiled.getText()))-(Float.parseFloat(gitticonfiled.getText()))+remaining;
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"gitti";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "UPDATE "+tablename
        +" SET Date=?, Receive=?, Consume=?, Size=?, Rate=?, VehicleNo=?, SupplerName=?, Receipt=?, Remaining=? WHERE Date=?";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dategitti.getDateEditor().getUiComponent()).getText());
pst.setString(2,gittirecfiled.getText());
pst.setString(3,gitticonfiled.getText());
pst.setString(4,gittisizefiled.getText());
pst.setString(5,gittiratefield.getText());
pst.setString(6,gittivehiclefiled.getText());
pst.setString(7,gittisupplfiled.getText());
pst.setString(8,gittibillfield.getText());
pst.setFloat(9,remain);
pst.setString(10,((JTextField) dategitti.getDateEditor().getUiComponent()).getText());
pst.executeUpdate();
showTableData();
refresh();
return ;
}

} 


    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_gittibtnupdateActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        try {
       float remain;
       remian();
       //System.out.println(remaining);
    remain=(Float.parseFloat(gittirecfiled.getText()))-(Float.parseFloat(gitticonfiled.getText()))+remaining;
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"gitti";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename
        +" WHERE Date=?";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dategitti.getDateEditor().getUiComponent()).getText());
pst.executeUpdate();
showTableData();
refresh();
return ;
}

} 


    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btndelActionPerformed

    private void gittirecfiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gittirecfiledKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_gittirecfiledKeyTyped

    private void gitticonfiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gitticonfiledKeyTyped
        char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_gitticonfiledKeyTyped

    private void gittisizefiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gittisizefiledKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_gittisizefiledKeyTyped

    private void gittiratefieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gittiratefieldKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_gittiratefieldKeyTyped

    private void gittirecfiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gittirecfiledFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_gittirecfiledFocusLost

    private void gitticonfiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gitticonfiledFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_gitticonfiledFocusLost

    private void gittisizefiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gittisizefiledFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_gittisizefiledFocusLost

    private void gittiratefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gittiratefieldFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_gittiratefieldFocusLost
private void remian(){
try{
   if(combosite.getSelectedItem()!=null){
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"gitti";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT Remaining FROM "+tablename+" ORDER BY Remaining DESC LIMIT 1";
    //System.out.println(sql);
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
remaining=rs.getInt(1);
//System.out.println(remaining);
}}}
   else{
   return;
   }

}
catch(Exception ex){
    remaining=0;
//JOptionPane.showMessageDialog(null, ex);
 
}


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gitti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gitti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gitti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gitti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gitti().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Gitti.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
public void showTableData(){

 try{
    
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"gitti";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
Gittitable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
 JOptionPane.showMessageDialog(null,"Please Add A Site First");
}

 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Gittitable;
    private javax.swing.JLabel SiteNamelabel;
    private javax.swing.JLabel SiteNamelabel1;
    private javax.swing.JLabel SiteNamelabel2;
    private javax.swing.JLabel SiteNamelabel3;
    private javax.swing.JLabel SiteNamelabel4;
    private javax.swing.JLabel SiteNamelabel5;
    private javax.swing.JLabel SiteNamelabel6;
    private javax.swing.JLabel SiteNamelabel7;
    private javax.swing.JLabel SiteNamelabel8;
    private javax.swing.JButton btndel;
    private javax.swing.JComboBox combosite;
    private com.toedter.calendar.JDateChooser dategitti;
    private javax.swing.JTextField gittibillfield;
    private javax.swing.JButton gittibtnbck;
    private javax.swing.JButton gittibtnsubmit;
    private javax.swing.JButton gittibtnupdate;
    private javax.swing.JTextField gitticonfiled;
    private javax.swing.JTextField gittiratefield;
    private javax.swing.JTextField gittirecfiled;
    private javax.swing.JTextField gittisizefiled;
    private javax.swing.JTextField gittisupplfiled;
    private javax.swing.JTextField gittivehiclefiled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
