
import java.awt.Dialog;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import static javax.swing.text.html.HTML.Tag.SELECT;
import static jdk.nashorn.internal.parser.TokenType.IF;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class NewcontractorForm extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
 ResultSet rs1=null;
  validateFields vf=new validateFields();
  int id=0;

    /**
     * Creates new form contractorForm
     */
    public NewcontractorForm() {
       try{ 
           
        initComponents();
        ShowdropDown();
           
        showTableData();
        
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(null, "Please Add Site First");}
        
    }
    public void showTableData(){
try{
    
        String name=comboxnewcont.getSelectedItem().toString();
        String tablename=name+"contractor";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
newcontable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
JOptionPane.showMessageDialog(null,"Please Add A Site First");

}
 
}
    public void refresh(){
    contaccountfield.setText("");
    contaddressfield.setText("");
    contadharfield.setText("");
    contnamefield.setText("");
    contsalaryfield.setText("");
    contmobilefield.setText("");
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contadharfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncontsubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contaddressfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contnamefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contaccountfield = new javax.swing.JTextField();
        contmobilefield = new javax.swing.JTextField();
        contsalaryfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btncontback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newcontable = new javax.swing.JTable();
        btncontdel = new javax.swing.JButton();
        btncontupdate = new javax.swing.JButton();
        condailyreport = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboxnewcont = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contadharfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contadharfieldFocusLost(evt);
            }
        });
        contadharfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadharfieldActionPerformed(evt);
            }
        });
        contadharfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contadharfieldKeyTyped(evt);
            }
        });

        jLabel3.setText("Aadhar No.");

        btncontsubmit.setText("Submit");
        btncontsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontsubmitActionPerformed(evt);
            }
        });

        jLabel5.setText("Mobile no");

        jLabel6.setText("Salary");

        jLabel2.setText("Name");

        jLabel8.setText("Address");

        contnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contnamefieldFocusLost(evt);
            }
        });
        contnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contnamefieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Account No.");

        contaccountfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contaccountfieldKeyTyped(evt);
            }
        });

        contmobilefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contmobilefieldFocusLost(evt);
            }
        });
        contmobilefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contmobilefieldActionPerformed(evt);
            }
        });
        contmobilefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contmobilefieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contmobilefieldKeyTyped(evt);
            }
        });

        contsalaryfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contsalaryfieldActionPerformed(evt);
            }
        });
        contsalaryfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfieldKeyTyped(evt);
            }
        });

        jLabel1.setText("Add New Contractor");

        btncontback.setText("Back");
        btncontback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontbackActionPerformed(evt);
            }
        });

        newcontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Account No", "Adhar No", "Address", "Mobile No", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        newcontable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newcontableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(newcontable);

        btncontdel.setText("Delete");
        btncontdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontdelActionPerformed(evt);
            }
        });

        btncontupdate.setText("Update");
        btncontupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontupdateActionPerformed(evt);
            }
        });

        condailyreport.setText("Contractor Daily Report ");
        condailyreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condailyreportActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Site Name");

        comboxnewcont.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxnewcontItemStateChanged(evt);
            }
        });
        comboxnewcont.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboxnewcontPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncontback)
                        .addGap(98, 98, 98)
                        .addComponent(condailyreport, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncontsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btncontupdate)
                                .addGap(57, 57, 57)
                                .addComponent(btncontdel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contnamefield)
                                    .addComponent(contadharfield)
                                    .addComponent(contaccountfield)
                                    .addComponent(contaddressfield)
                                    .addComponent(contsalaryfield)
                                    .addComponent(contmobilefield)
                                    .addComponent(comboxnewcont, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboxnewcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(contaccountfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contadharfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(contaddressfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(contmobilefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contsalaryfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncontsubmit)
                    .addComponent(btncontdel)
                    .addComponent(btncontupdate))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncontback)
                    .addComponent(condailyreport))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncontbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontbackActionPerformed
       new viewSiteform().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncontbackActionPerformed

    private void btncontsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontsubmitActionPerformed
    try {
       if(contnamefield.getText().length()==0 || contmobilefield.getText().length()==0){
            JOptionPane.showMessageDialog(null,  "Name or Mobile number field is empty");
            return;
       }
       
          
        String name=comboxnewcont.getSelectedItem().toString();
        String tablename=name+"contractor";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(name, address, mobile, aadhar, salary, account)"
+"VALUES (?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,contnamefield.getText());
pst.setString(2,contaddressfield.getText());
pst.setString(3,contmobilefield.getText());
pst.setString(4,contadharfield.getText());
pst.setString(5,contsalaryfield.getText());
pst.setString(6,contaccountfield.getText());
pst.executeUpdate();
    //System.out.println("upper");
showTableData();
//showTable st=new showTable();
    //st.savefle(newcontable, new File("E:\\project\\"+tablename+".xls"),comboxnewcont,"contractor");
refresh();
return ;
}

} 

pst.executeUpdate("CREATE TABLE "+ tablename +
                "("+"ID INT NOT NULL AUTO_INCREMENT,name TEXT(25),address VARCHAR(100),mobile VARCHAR(100),aadhar VARCHAR(100),salary VARCHAR(100),account VARCHAR(100),PRIMARY KEY(ID))");
String sql = "INSERT INTO "+tablename
        +"(name, address, mobile, aadhar, salary, account)"
+"VALUES (?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,contnamefield.getText());
pst.setString(2,contaddressfield.getText());
pst.setString(3,contmobilefield.getText());
pst.setString(4,contadharfield.getText());
pst.setString(5,contsalaryfield.getText());
pst.setString(6,contaccountfield.getText());
pst.executeUpdate();
showTableData();
refresh();


       
        
        
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null,ex);
        //JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    } 
       

    }//GEN-LAST:event_btncontsubmitActionPerformed

    private void btncontdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontdelActionPerformed
         try {
        if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
            }
        String name=comboxnewcont.getSelectedItem().toString();
        String tablename=name+"contractor";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename+" WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
            pst.setInt(1,id);
            pst.executeUpdate();
            showTableData();
            JOptionPane.showMessageDialog(null, "delete successfully");
refresh();
id=0;
return ;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    }
    }//GEN-LAST:event_btncontdelActionPerformed

    private void btncontupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontupdateActionPerformed
        try {
        if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
            }
        String name=comboxnewcont.getSelectedItem().toString();
        String tablename=name+"contractor";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "UPDATE "+tablename
        +" SET name=?,address=?,mobile=?,aadhar=?,salary=?,account=? WHERE ID=?";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
    //System.out.println(sql);
pst = con.prepareStatement(sql);
pst.setString(1,contnamefield.getText());
pst.setString(2,contaddressfield.getText());
pst.setString(3,contmobilefield.getText());
pst.setString(4,contadharfield.getText());
pst.setString(5,contsalaryfield.getText());
pst.setString(6,contaccountfield.getText());
pst.setInt(7,id);
pst.executeUpdate();
showTableData();
refresh();
id=0;
return ;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    }
       
    }//GEN-LAST:event_btncontupdateActionPerformed

    private void condailyreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condailyreportActionPerformed
   
    try {
        new ContractorDailyReport().setVisible(true);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Please Add Contractor First");
        
    }
        this.setVisible(false);
    }//GEN-LAST:event_condailyreportActionPerformed

    private void contnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contnamefieldActionPerformed

    private void comboxnewcontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxnewcontItemStateChanged
     
    }//GEN-LAST:event_comboxnewcontItemStateChanged

    private void comboxnewcontPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboxnewcontPopupMenuWillBecomeInvisible
        try{
    
        String name=comboxnewcont.getSelectedItem().toString();
        String tablename=name+"contractor";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
newcontable.setModel(DbUtils.resultSetToTableModel(rs));
}}}
catch(Exception ex){
JOptionPane.showMessageDialog(null,"Please Add A Site First");
 
}
    }//GEN-LAST:event_comboxnewcontPopupMenuWillBecomeInvisible

    private void newcontableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcontableMouseClicked
       int i=newcontable.getSelectedRow();
        TableModel model=newcontable.getModel();
        id=Integer.parseInt(model.getValueAt(i,0).toString());
        contnamefield.setText(model.getValueAt(i,1).toString());
        contaddressfield.setText(model.getValueAt(i,2).toString());
        contmobilefield.setText(model.getValueAt(i,3).toString());
        contadharfield.setText(model.getValueAt(i,4).toString());
        contsalaryfield.setText(model.getValueAt(i,5).toString());
        contaccountfield.setText(model.getValueAt(i,6).toString());
        
        
    }//GEN-LAST:event_newcontableMouseClicked

    private void contmobilefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contmobilefieldActionPerformed
      
    }//GEN-LAST:event_contmobilefieldActionPerformed

    private void contmobilefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contmobilefieldKeyPressed
       
  // vf.validateMoblie(contmobilefield,"Mobile Number Must be in 10 Digit");
        
   
    
    }//GEN-LAST:event_contmobilefieldKeyPressed
    
    private void contmobilefieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contmobilefieldKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_contmobilefieldKeyTyped

    private void contmobilefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contmobilefieldFocusLost
       vf.validateMoblie(contmobilefield,"Mobile Number Must be in 10 Digit");
        
    }//GEN-LAST:event_contmobilefieldFocusLost

    private void contadharfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadharfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contadharfieldActionPerformed

    private void contadharfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadharfieldKeyTyped
    char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_contadharfieldKeyTyped
int count=0;
    private void contsalaryfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
JOptionPane.showMessageDialog(null,"Two Decimals are not allow");}
    }//GEN-LAST:event_contsalaryfieldKeyTyped

    private void contaccountfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contaccountfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }// TODO add your handling code here:
    }//GEN-LAST:event_contaccountfieldKeyTyped

    private void contadharfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contadharfieldFocusLost
      vf.validateAdhar(contadharfield,"Adhar Must be in 12 Digits");
    }//GEN-LAST:event_contadharfieldFocusLost

    private void contnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contnamefieldFocusLost
vf.validateName(contnamefield,"Contractor Name Can not be Empty");        // TODO add your handling code here:
    }//GEN-LAST:event_contnamefieldFocusLost

    private void contsalaryfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contsalaryfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfieldActionPerformed

    public void ShowdropDown() {
        try {
          con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM site";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name=rs.getString("SiteName");
    
comboxnewcont.addItem(name); 
}}
         catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Please Add Site First");
             return;
        }

}


    

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontback;
    private javax.swing.JButton btncontdel;
    private javax.swing.JButton btncontsubmit;
    private javax.swing.JButton btncontupdate;
    private javax.swing.JComboBox comboxnewcont;
    private javax.swing.JButton condailyreport;
    private javax.swing.JTextField contaccountfield;
    private javax.swing.JTextField contaddressfield;
    private javax.swing.JTextField contadharfield;
    private javax.swing.JTextField contmobilefield;
    private javax.swing.JTextField contnamefield;
    private javax.swing.JTextField contsalaryfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable newcontable;
    // End of variables declaration//GEN-END:variables
}
