
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class otherForm extends javax.swing.JFrame {
     Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
showTable st=new showTable();
int count=0;
float TinShed;
float raftingSheet;
float Openyard;
float labour;
float Tractor;
float totalSkilled;
float totalunSkilled;
float TotalLabour;
float GrandTotal;
float total;
int id;
    /**
     * Creates new form otherForm
     */
   
     void total(){
       int skilledPers=Integer.parseInt(conSkillspin.getText());
     int skilledrate= Integer.parseInt(SkillrateCon.getText());
      int unskilledPers=Integer.parseInt(ConUnskillSpin.getText());
     int unskilledrate= Integer.parseInt(unskillratecon.getText());
     Tractor=Float.parseFloat(TactorOtherfirld.getText())*Float.parseFloat(hoursfieild.getText())*Float.parseFloat(tatratefiled.getText());
     totalSkilled=skilledPers*skilledrate;
    
      totalunSkilled=unskilledPers*unskilledrate;
     
     TotalLabour= totalSkilled+totalunSkilled;
     skillTotalcon.setText(""+totalSkilled);
     unSkillTotalco.setText(""+totalunSkilled);
     GrandTotal=Float.parseFloat(RaftingotherFiled.getText())+Float.parseFloat(tinOtherField.getText())+Float.parseFloat(OpenYardOtherFied.getText())+TotalLabour+Tractor+Float.parseFloat(TactorOtherfirld1.getText());
    
         
    }
    public otherForm() {
        initComponents();
        st.ShowdropDown(AddSite);
        st.showTableData(othertable, AddSite, "otherwork");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tinOtherField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RaftingotherFiled = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        OpenYardOtherFied = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TactorOtherfirld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SubmitOtherbutton = new javax.swing.JButton();
        OtherdelButton = new javax.swing.JButton();
        OtherBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        othertable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        AddSite = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        SkillrateCon = new javax.swing.JTextField();
        skillTotalcon = new javax.swing.JTextField();
        unskillratecon = new javax.swing.JTextField();
        unSkillTotalco = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        skilleddaily = new javax.swing.JLabel();
        conSkillspin = new javax.swing.JTextField();
        unskilldaily = new javax.swing.JLabel();
        ConUnskillSpin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateOther = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        TactorOtherfirld1 = new javax.swing.JTextField();
        hoursfieild = new javax.swing.JTextField();
        tatratefiled = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tin shed");

        tinOtherField.setText("0");
        tinOtherField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tinOtherFieldFocusLost(evt);
            }
        });
        tinOtherField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tinOtherFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("Rafting sheet");

        RaftingotherFiled.setText("0");
        RaftingotherFiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RaftingotherFiledFocusLost(evt);
            }
        });
        RaftingotherFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaftingotherFiledActionPerformed(evt);
            }
        });
        RaftingotherFiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RaftingotherFiledKeyTyped(evt);
            }
        });

        jLabel3.setText("Open yard");

        OpenYardOtherFied.setText("0");
        OpenYardOtherFied.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                OpenYardOtherFiedFocusLost(evt);
            }
        });
        OpenYardOtherFied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenYardOtherFiedActionPerformed(evt);
            }
        });
        OpenYardOtherFied.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OpenYardOtherFiedKeyTyped(evt);
            }
        });

        jLabel5.setText("Tractor");

        TactorOtherfirld.setText("0");
        TactorOtherfirld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TactorOtherfirldKeyTyped(evt);
            }
        });

        jLabel8.setText("Hour");

        jLabel9.setText("Others WorkDone");

        SubmitOtherbutton.setText("Submit");
        SubmitOtherbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitOtherbuttonActionPerformed(evt);
            }
        });

        OtherdelButton.setText("Delete");
        OtherdelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherdelButtonActionPerformed(evt);
            }
        });

        OtherBackButton.setText("Back");
        OtherBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherBackButtonActionPerformed(evt);
            }
        });

        othertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Tin Shed", "Rafting Sheet", "Open Yard", "JCB", "Labour", "Tractor", "TotalAmount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        othertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                othertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(othertable);
        if (othertable.getColumnModel().getColumnCount() > 0) {
            othertable.getColumnModel().getColumn(6).setResizable(false);
            othertable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel10.setText("Select Site");

        AddSite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                AddSitePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel11.setText("Date");

        SkillrateCon.setText("0");
        SkillrateCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkillrateConActionPerformed(evt);
            }
        });
        SkillrateCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SkillrateConKeyTyped(evt);
            }
        });

        skillTotalcon.setText("0");

        unskillratecon.setText("0");
        unskillratecon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unskillrateconKeyTyped(evt);
            }
        });

        unSkillTotalco.setText("0");

        jLabel12.setText("Labour Type ");

        skilleddaily.setText("Skilled");

        conSkillspin.setText("0");
        conSkillspin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conSkillspinKeyTyped(evt);
            }
        });

        unskilldaily.setText("UnSkilled ");

        ConUnskillSpin.setText("0");
        ConUnskillSpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ConUnskillSpinKeyTyped(evt);
            }
        });

        jLabel13.setText("Rate ");

        jLabel14.setText("Total");

        jLabel6.setText("JCB");

        TactorOtherfirld1.setText("0");
        TactorOtherfirld1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TactorOtherfirld1FocusLost(evt);
            }
        });
        TactorOtherfirld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TactorOtherfirld1ActionPerformed(evt);
            }
        });
        TactorOtherfirld1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TactorOtherfirld1KeyTyped(evt);
            }
        });

        hoursfieild.setText("0");
        hoursfieild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hoursfieildFocusLost(evt);
            }
        });
        hoursfieild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursfieildKeyTyped(evt);
            }
        });

        tatratefiled.setText("0");
        tatratefiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tatratefiledFocusLost(evt);
            }
        });
        tatratefiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tatratefiledKeyTyped(evt);
            }
        });

        jLabel15.setText("Rate");

        jLabel16.setText("Numbers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateOther, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddSite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(29, 29, 29))
                                    .addComponent(TactorOtherfirld1)
                                    .addComponent(OpenYardOtherFied, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RaftingotherFiled, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tinOtherField, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(OtherBackButton)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TactorOtherfirld, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hoursfieild)
                                        .addGap(36, 36, 36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(unSkillTotalco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tatratefiled, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(skillTotalcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SubmitOtherbutton)
                                        .addGap(18, 18, 18)
                                        .addComponent(OtherdelButton))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(unskilldaily)
                                            .addComponent(skilleddaily, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(conSkillspin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ConUnskillSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SkillrateCon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(unskillratecon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(AddSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(dateOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tinOtherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RaftingotherFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(OpenYardOtherFied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TactorOtherfirld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(skilleddaily)
                            .addComponent(SkillrateCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conSkillspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillTotalcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unskilldaily)
                            .addComponent(unskillratecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConUnskillSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unSkillTotalco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TactorOtherfirld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoursfieild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tatratefiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitOtherbutton)
                            .addComponent(OtherdelButton))
                        .addGap(26, 26, 26)
                        .addComponent(OtherBackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenYardOtherFiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenYardOtherFiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenYardOtherFiedActionPerformed

    private void RaftingotherFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaftingotherFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RaftingotherFiledActionPerformed

    private void SubmitOtherbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitOtherbuttonActionPerformed
         try {
             if(((JTextField) dateOther.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
                    }
                    
                 total();
                     remian();

                     float New_total=total+GrandTotal;
       
        String name=AddSite.getSelectedItem().toString();
        
        String tablename=name+"otherwork";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(Date, TinShed, RaftingSheet, OpenYard, JCB,Labour,Tractor,TotalAmount)"
+"VALUES (?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateOther.getDateEditor().getUiComponent()).getText());
pst.setString(2,tinOtherField.getText());
pst.setString(3,RaftingotherFiled.getText());
pst.setString(4,OpenYardOtherFied.getText());
pst.setString(5,TactorOtherfirld1.getText());

pst.setFloat(6,TotalLabour);
pst.setFloat(7,Tractor);
pst.setFloat(8,New_total);

pst.executeUpdate();
st.showTableData(othertable, AddSite, "otherwork");
refresh();
return ;
}

} 
  //System.out.println("chal bc");
String sql1="CREATE TABLE "+ tablename +
                "("+"ID INT NOT NULL AUTO_INCREMENT,Date TEXT(20),TinShed FLOAT(25),RaftingSheet FLOAT(10),OpenYard FLOAT(15),JCB FLOAT(30),"
        + "Labour FLOAT(30),Tractor FLOAT(30),TotalAmount FLOAT(30),PRIMARY KEY(ID))";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql1);
//System.out.println(sql1);
pst.executeUpdate(sql1);


System.out.println("chal bc");
String sql = "INSERT INTO "+tablename
        +"(Date, TinShed, RaftingSheet, OpenYard, JCB,Labour,Tractor,TotalAmount)"
+"VALUES (?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateOther.getDateEditor().getUiComponent()).getText());
pst.setString(2,tinOtherField.getText());
pst.setString(3,RaftingotherFiled.getText());
pst.setString(4,OpenYardOtherFied.getText());
pst.setString(5,TactorOtherfirld1.getText());

pst.setFloat(6,TotalLabour);
pst.setFloat(7,Tractor);
pst.setFloat(8,New_total);
pst.executeUpdate();
st.showTableData(othertable, AddSite, "otherwork");
refresh();



       
        
        
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
              
        
    }//GEN-LAST:event_SubmitOtherbuttonActionPerformed

    private void OtherdelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherdelButtonActionPerformed
        try {
         if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
            }
        String name=AddSite.getSelectedItem().toString();
        String tablename=name+"otherwork";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename+" WHERE date=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
            pst.setString(1,((JTextField) dateOther.getDateEditor().getUiComponent()).getText());
            pst.executeUpdate();
            st.showTableData(othertable, AddSite, "otherwork");
            JOptionPane.showMessageDialog(null, "delete successfully");

          refresh();
id=0;
            return ;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    }
    }//GEN-LAST:event_OtherdelButtonActionPerformed

    private void OtherBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherBackButtonActionPerformed
        new WorkDone().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OtherBackButtonActionPerformed

    private void AddSitePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_AddSitePopupMenuWillBecomeInvisible
        st.FillTableUSingcombo(AddSite, othertable, "otherwork");
       
    }//GEN-LAST:event_AddSitePopupMenuWillBecomeInvisible

    private void othertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othertableMouseClicked
       int i = othertable.getSelectedRow();
        TableModel model = othertable.getModel();
        id=Integer.parseInt(model.getValueAt(i,0).toString());
       
        
        String date = model.getValueAt(i, 1).toString();
        ((JTextField) dateOther.getDateEditor().getUiComponent()).setText(date);
        tinOtherField.setText(model.getValueAt(i,2).toString());
        RaftingotherFiled.setText(model.getValueAt(i,3).toString());
        OpenYardOtherFied.setText(model.getValueAt(i,4).toString());
        TactorOtherfirld1.setText(model.getValueAt(i,5).toString());
      
        
    }//GEN-LAST:event_othertableMouseClicked

    private void SkillrateConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkillrateConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkillrateConActionPerformed

    private void TactorOtherfirld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TactorOtherfirld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TactorOtherfirld1ActionPerformed

    private void tinOtherFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinOtherFieldKeyTyped
        char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_tinOtherFieldKeyTyped

    private void RaftingotherFiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RaftingotherFiledKeyTyped
        char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_RaftingotherFiledKeyTyped

    private void OpenYardOtherFiedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OpenYardOtherFiedKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_OpenYardOtherFiedKeyTyped

    private void TactorOtherfirld1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TactorOtherfirld1KeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
    }//GEN-LAST:event_TactorOtherfirld1KeyTyped

    private void conSkillspinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conSkillspinKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_conSkillspinKeyTyped

    private void SkillrateConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SkillrateConKeyTyped
        char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_SkillrateConKeyTyped

    private void ConUnskillSpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConUnskillSpinKeyTyped
        char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_ConUnskillSpinKeyTyped

    private void unskillrateconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unskillrateconKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
    }//GEN-LAST:event_unskillrateconKeyTyped

    private void TactorOtherfirldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TactorOtherfirldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_TactorOtherfirldKeyTyped

    private void hoursfieildKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursfieildKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_hoursfieildKeyTyped

    private void tatratefiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tatratefiledKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_tatratefiledKeyTyped

    private void tinOtherFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinOtherFieldFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_tinOtherFieldFocusLost

    private void RaftingotherFiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RaftingotherFiledFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_RaftingotherFiledFocusLost

    private void OpenYardOtherFiedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OpenYardOtherFiedFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_OpenYardOtherFiedFocusLost

    private void TactorOtherfirld1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TactorOtherfirld1FocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_TactorOtherfirld1FocusLost

    private void hoursfieildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hoursfieildFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_hoursfieildFocusLost

    private void tatratefiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tatratefiledFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_tatratefiledFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otherForm().setVisible(true);
            }
        });
    }

    private void refresh(){
    

 OpenYardOtherFied.setText("0");
 
 TactorOtherfirld.setText("0");


tinOtherField.setText("0");

RaftingotherFiled.setText("0");
TactorOtherfirld1.setText("0");
conSkillspin.setText("0");
SkillrateCon.setText("0");
ConUnskillSpin.setText("0");
unskillratecon.setText("0");
unSkillTotalco.setText("0");
skillTotalcon.setText("0");
unskillratecon.setText("0");
hoursfieild.setText("0");
tatratefiled.setText("0");

        
 //dateOther.setDateFormatString("");
}
    private void remian(){
try{
   if(AddSite.getSelectedItem()!=null){
        String name=AddSite.getSelectedItem().toString();
        String tablename=name+"otherwork";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT TotalAmount FROM "+tablename+" ORDER BY ID DESC LIMIT 1";
    //System.out.println(sql);
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
total=rs.getFloat(1);
 //System.out.println(total);
//System.out.println(remaining);
}}}
   else{
   return;
   }

}
catch(Exception ex){
    //System.out.println("mai chal tha");
    total=0;
//JOptionPane.showMessageDialog(null, ex);
 
}


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AddSite;
    private javax.swing.JTextField ConUnskillSpin;
    private javax.swing.JTextField OpenYardOtherFied;
    private javax.swing.JButton OtherBackButton;
    private javax.swing.JButton OtherdelButton;
    private javax.swing.JTextField RaftingotherFiled;
    private javax.swing.JTextField SkillrateCon;
    private javax.swing.JButton SubmitOtherbutton;
    private javax.swing.JTextField TactorOtherfirld;
    private javax.swing.JTextField TactorOtherfirld1;
    private javax.swing.JTextField conSkillspin;
    private com.toedter.calendar.JDateChooser dateOther;
    private javax.swing.JTextField hoursfieild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable othertable;
    private javax.swing.JTextField skillTotalcon;
    private javax.swing.JLabel skilleddaily;
    private javax.swing.JTextField tatratefiled;
    private javax.swing.JTextField tinOtherField;
    private javax.swing.JTextField unSkillTotalco;
    private javax.swing.JLabel unskilldaily;
    private javax.swing.JTextField unskillratecon;
    // End of variables declaration//GEN-END:variables
}
