
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Clock;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


public class RoadForm extends javax.swing.JFrame {
      Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
 float excavation;
    float dressing;
    float wbmlayer1;
    float wbmlayer2;
    float wbmlayer3;
    float wbmlayer4;
    float wbmlayer5;
    float waterBOunding;
    float FinalTouch;
    float totalamount;
    int count=0;
    int id=0;
    float total;
    showTable st=new showTable();

    /**
     * Creates new form RoadForm
     */

public void refresh(){
    //PccRateEquip.setText("");
    //dateroadfield.setDateFormatString("");
    wbmroadfield.setText("0");
    wbm4roadfield.setText("0");
    wbm3roadfield.setText("0");
    wbm2roadfield.setText("0");
    wbm1roadfield.setText("0");
   
    waterboundingfield.setText("0");
    totalroadfield.setText("0");
    contaddressfield3.setText("0");
    contmobilefield2.setText("0");
   
    contsalaryfield8.setText("0");
    contsalaryfield7.setText("0");
    contsalaryfield6.setText("0");
    contsalaryfield5.setText("0");
    contmobilefield3.setText("0");
    contmobilefield2.setText("0");
    contadharfield1.setText("0");
    contaddressfield3.setText("0");
    contaddressfield2.setText("0");
    finaltouchroadfield.setText("0");
    excavationroadfield.setText("0");
    dressignroadfield.setText("0");
    
    
    
    }
    public RoadForm() throws SQLException {
        initComponents();
       st.ShowdropDown(SelectsiteRoad);
        st.showTableData(tableroad, SelectsiteRoad, "road");
    
    }

    float total(){
         excavation =Float.parseFloat(excavationroadfield.getText())*Float.parseFloat(contadharfield1.getText());
         dressing =Float.parseFloat(dressignroadfield.getText())*Float.parseFloat(contaddressfield2.getText());
         wbmlayer1 =Float.parseFloat(wbm1roadfield.getText())*Float.parseFloat(contmobilefield2.getText());
         wbmlayer2 =Float.parseFloat(wbm2roadfield.getText())*Float.parseFloat(contsalaryfield6.getText());
         wbmlayer3 =Float.parseFloat(wbm3roadfield.getText())*Float.parseFloat(contaddressfield3.getText());
         wbmlayer4 =Float.parseFloat(wbm4roadfield.getText())*Float.parseFloat(contmobilefield3.getText());
         wbmlayer5 =Float.parseFloat(wbmroadfield.getText())*Float.parseFloat(contsalaryfield5.getText());
          waterBOunding =Float.parseFloat(waterboundingfield.getText())*Float.parseFloat(contsalaryfield8.getText());
        FinalTouch=Float.parseFloat(finaltouchroadfield.getText())*Float.parseFloat(contsalaryfield7.getText());
          totalamount=excavation+dressing+wbmlayer1+wbmlayer2+wbmlayer3+wbmlayer4+wbmlayer5+waterBOunding;
          return totalamount;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roaddelbuttton = new javax.swing.JButton();
        wbmroadfield = new javax.swing.JTextField();
        excavationroadfield = new javax.swing.JTextField();
        excavationtower = new javax.swing.JLabel();
        roadsubmitbutton = new javax.swing.JButton();
        barbindtower = new javax.swing.JLabel();
        Shuttringtower = new javax.swing.JLabel();
        dressignroadfield = new javax.swing.JTextField();
        totaltower = new javax.swing.JLabel();
        pcctower = new javax.swing.JLabel();
        roadupdatebutton = new javax.swing.JButton();
        contsalaryfield5 = new javax.swing.JTextField();
        namefieldRoad = new javax.swing.JTextField();
        contadharfield1 = new javax.swing.JTextField();
        contaddressfield2 = new javax.swing.JTextField();
        backroadbutton = new javax.swing.JButton();
        contmobilefield2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableroad = new javax.swing.JTable();
        completetower = new javax.swing.JLabel();
        contaddressfield3 = new javax.swing.JTextField();
        contsalaryfield6 = new javax.swing.JTextField();
        contmobilefield3 = new javax.swing.JTextField();
        labelboltingfirst = new javax.swing.JLabel();
        totalroadfield = new javax.swing.JTextField();
        labelfinal = new javax.swing.JLabel();
        wbm1roadfield = new javax.swing.JTextField();
        wbm3roadfield = new javax.swing.JTextField();
        wbm2roadfield = new javax.swing.JTextField();
        wbm4roadfield = new javax.swing.JTextField();
        headingroad = new javax.swing.JLabel();
        labelraft = new javax.swing.JLabel();
        waterboundingfield = new javax.swing.JTextField();
        labelfinal1 = new javax.swing.JLabel();
        contsalaryfield7 = new javax.swing.JTextField();
        finaltouchroadfield = new javax.swing.JTextField();
        labelfinal2 = new javax.swing.JLabel();
        contsalaryfield8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SelectsiteRoad = new javax.swing.JComboBox<>();
        datetowerlabel = new javax.swing.JLabel();
        dateroadfield = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roaddelbuttton.setText("Delete");
        roaddelbuttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roaddelbutttonActionPerformed(evt);
            }
        });

        wbmroadfield.setText("0");
        wbmroadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wbmroadfieldFocusLost(evt);
            }
        });
        wbmroadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wbmroadfieldKeyTyped(evt);
            }
        });

        excavationroadfield.setText("0");
        excavationroadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                excavationroadfieldFocusLost(evt);
            }
        });
        excavationroadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                excavationroadfieldKeyTyped(evt);
            }
        });

        excavationtower.setText("Excavation");

        roadsubmitbutton.setText("Submit");
        roadsubmitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roadsubmitbuttonActionPerformed(evt);
            }
        });

        barbindtower.setText("WBM Layer 1");

        Shuttringtower.setText("WBM Layer 2");

        dressignroadfield.setText("0");
        dressignroadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dressignroadfieldFocusLost(evt);
            }
        });
        dressignroadfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dressignroadfieldActionPerformed(evt);
            }
        });
        dressignroadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dressignroadfieldKeyTyped(evt);
            }
        });

        totaltower.setText("Name");

        pcctower.setText("Dressing");

        roadupdatebutton.setText("Update");
        roadupdatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roadupdatebuttonActionPerformed(evt);
            }
        });

        contsalaryfield5.setText("0");
        contsalaryfield5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contsalaryfield5FocusLost(evt);
            }
        });
        contsalaryfield5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contsalaryfield5ActionPerformed(evt);
            }
        });
        contsalaryfield5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfield5KeyTyped(evt);
            }
        });

        contadharfield1.setText("0");
        contadharfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contadharfield1FocusLost(evt);
            }
        });
        contadharfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contadharfield1KeyTyped(evt);
            }
        });

        contaddressfield2.setText("0");
        contaddressfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contaddressfield2FocusLost(evt);
            }
        });
        contaddressfield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contaddressfield2KeyTyped(evt);
            }
        });

        backroadbutton.setText("Back");
        backroadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backroadbuttonActionPerformed(evt);
            }
        });

        contmobilefield2.setText("0");
        contmobilefield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contmobilefield2FocusLost(evt);
            }
        });
        contmobilefield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contmobilefield2KeyTyped(evt);
            }
        });

        tableroad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name ", "Total", "Excavation", "Dressing", "WBM Layer 1", "WBM Layer 2", "WBM Layer 3", "WBM Layer 4", "WBM Layer 5", "Water bounding", "final touch", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableroad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableroadMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableroad);

        completetower.setText("Total");

        contaddressfield3.setText("0");
        contaddressfield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contaddressfield3FocusLost(evt);
            }
        });
        contaddressfield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contaddressfield3KeyTyped(evt);
            }
        });

        contsalaryfield6.setText("0");
        contsalaryfield6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contsalaryfield6FocusLost(evt);
            }
        });
        contsalaryfield6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfield6KeyTyped(evt);
            }
        });

        contmobilefield3.setText("0");
        contmobilefield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contmobilefield3FocusLost(evt);
            }
        });
        contmobilefield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contmobilefield3KeyTyped(evt);
            }
        });

        labelboltingfirst.setText("WBM Layer 4");

        totalroadfield.setText("0");
        totalroadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalroadfieldKeyTyped(evt);
            }
        });

        labelfinal.setText("WBM Layer 5");

        wbm1roadfield.setText("0");
        wbm1roadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wbm1roadfieldFocusLost(evt);
            }
        });
        wbm1roadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wbm1roadfieldKeyTyped(evt);
            }
        });

        wbm3roadfield.setText("0");
        wbm3roadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wbm3roadfieldFocusLost(evt);
            }
        });
        wbm3roadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wbm3roadfieldKeyTyped(evt);
            }
        });

        wbm2roadfield.setText("0");
        wbm2roadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wbm2roadfieldFocusLost(evt);
            }
        });
        wbm2roadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wbm2roadfieldKeyTyped(evt);
            }
        });

        wbm4roadfield.setText("0");
        wbm4roadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wbm4roadfieldFocusLost(evt);
            }
        });
        wbm4roadfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wbm4roadfieldActionPerformed(evt);
            }
        });
        wbm4roadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wbm4roadfieldKeyTyped(evt);
            }
        });

        headingroad.setText("Add Road Details");

        labelraft.setText("WBM Layer 3");

        waterboundingfield.setText("0");
        waterboundingfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                waterboundingfieldFocusLost(evt);
            }
        });
        waterboundingfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterboundingfieldActionPerformed(evt);
            }
        });
        waterboundingfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                waterboundingfieldKeyTyped(evt);
            }
        });

        labelfinal1.setText("Water bounding");

        contsalaryfield7.setText("0");
        contsalaryfield7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contsalaryfield7FocusLost(evt);
            }
        });
        contsalaryfield7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfield7KeyTyped(evt);
            }
        });

        finaltouchroadfield.setText("0");
        finaltouchroadfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                finaltouchroadfieldFocusLost(evt);
            }
        });
        finaltouchroadfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finaltouchroadfieldActionPerformed(evt);
            }
        });
        finaltouchroadfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                finaltouchroadfieldKeyTyped(evt);
            }
        });

        labelfinal2.setText("Final touch");

        contsalaryfield8.setText("0");
        contsalaryfield8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contsalaryfield8FocusLost(evt);
            }
        });
        contsalaryfield8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfield8KeyTyped(evt);
            }
        });

        jLabel2.setText("Rate");

        jLabel1.setText("Select Site");

        SelectsiteRoad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                SelectsiteRoadPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        datetowerlabel.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backroadbutton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(completetower, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(datetowerlabel)
                                                .addComponent(totaltower))
                                            .addComponent(excavationtower, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pcctower, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(barbindtower, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Shuttringtower)
                                            .addComponent(labelraft, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelboltingfirst)
                                            .addComponent(labelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelfinal1)
                                            .addComponent(labelfinal2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wbmroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(finaltouchroadfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(waterboundingfield, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(SelectsiteRoad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(namefieldRoad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(totalroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(wbm3roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wbm4roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wbm2roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wbm1roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dressignroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(excavationroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(contaddressfield3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contsalaryfield6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contmobilefield2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contaddressfield2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contadharfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(contsalaryfield5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contmobilefield3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(contsalaryfield7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contsalaryfield8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(roadsubmitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(roadupdatebutton)
                                .addGap(57, 57, 57)
                                .addComponent(roaddelbuttton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(headingroad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingroad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelectsiteRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datetowerlabel))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totaltower)
                            .addComponent(namefieldRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(completetower)
                            .addComponent(totalroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(excavationroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excavationtower)
                            .addComponent(contadharfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcctower)
                            .addComponent(dressignroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contaddressfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barbindtower)
                            .addComponent(wbm1roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contmobilefield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Shuttringtower, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wbm2roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contsalaryfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelraft)
                            .addComponent(wbm3roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contaddressfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wbm4roadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelboltingfirst)
                            .addComponent(contmobilefield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wbmroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contsalaryfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waterboundingfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(contsalaryfield8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelfinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finaltouchroadfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contsalaryfield7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roadsubmitbutton)
                            .addComponent(roaddelbuttton)
                            .addComponent(roadupdatebutton))))
                .addGap(18, 18, 18)
                .addComponent(backroadbutton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roaddelbutttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roaddelbutttonActionPerformed
         try {
      if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
            }  
        String name=SelectsiteRoad.getSelectedItem().toString();
        String tablename=name+"road";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename+" WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
            pst.setInt(1,id);
            pst.executeUpdate();
            st.showTableData(tableroad, SelectsiteRoad, "road");
            JOptionPane.showMessageDialog(null, "delete successfully");
refresh();
id=0;

return ;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    }
    }//GEN-LAST:event_roaddelbutttonActionPerformed

    private void roadsubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roadsubmitbuttonActionPerformed

        try {
         
             
                    if(((JTextField) dateroadfield.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
                    }
                    if(namefieldRoad.getText().length()==0){
                        JOptionPane.showMessageDialog(null, "Name Can not be empty");
             return;
                    }
                      total();
                     remian();
                   float New_total=total+totalamount;
                     
                   
       
        String name=SelectsiteRoad.getSelectedItem().toString();
        
        String tablename=name+"road";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(Date,Name,TotalRoad, Excavation, Dressing, Wbmlayer1, Wbmlayer2,Wbmlayer3,Wbmlayer4,Wbmlayer5,WaterBOunding,FinalTouch,TotalAmount)"
+"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateroadfield.getDateEditor().getUiComponent()).getText());
pst.setString(2,namefieldRoad.getText());
pst.setInt(3,Integer.parseInt(totalroadfield.getText()));
pst.setFloat(4,excavation);
pst.setFloat(5,dressing);
pst.setFloat(6,wbmlayer1);
pst.setFloat(7,wbmlayer2);
pst.setFloat(8,wbmlayer3);
pst.setFloat(9,wbmlayer4);
pst.setFloat(10,wbmlayer5);
pst.setFloat(11,waterBOunding);
pst.setFloat(12,FinalTouch);
pst.setFloat(13,New_total);

pst.executeUpdate();
st.showTableData(tableroad, SelectsiteRoad, "road");
refresh();
return ;
}

} 
  //System.out.println("chal bc");
String sql1="CREATE TABLE "+ tablename +
                "("+"ID INT NOT NULL AUTO_INCREMENT,Date TEXT(20), Name TEXT(30),TotalRoad INT(25),Excavation FLOAT(10),Dressing FLOAT(15),Wbmlayer1 FLOAT(15),Wbmlayer2 FLOAT(10),Wbmlayer3 FLOAT(30),Wbmlayer4 FLOAT(30),Wbmlayer5 FLOAT(30),WaterBOunding FLOAT(30),FinalTouch FLOAT(30),TotalAmount FLOAT(30),PRIMARY KEY(ID))";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql1);
//System.out.println(sql1);
pst.executeUpdate(sql1);
String sql = "INSERT INTO "+tablename
        +"(Date,Name,TotalRoad, Excavation, Dressing, Wbmlayer1, Wbmlayer2,Wbmlayer3,Wbmlayer4,Wbmlayer5,WaterBOunding,FinalTouch,TotalAmount)"
+"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateroadfield.getDateEditor().getUiComponent()).getText());
pst.setString(2,namefieldRoad.getText());
pst.setInt(3,Integer.parseInt(totalroadfield.getText()));
pst.setFloat(4,excavation);
pst.setFloat(5,dressing);
pst.setFloat(6,wbmlayer1);
pst.setFloat(7,wbmlayer2);
pst.setFloat(8,wbmlayer3);
pst.setFloat(9,wbmlayer4);
pst.setFloat(10,wbmlayer5);
pst.setFloat(11,waterBOunding);
pst.setFloat(12,FinalTouch);
pst.setFloat(13,New_total);
pst.executeUpdate();
st.showTableData(tableroad, SelectsiteRoad, "road");
refresh();



       
        
        
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
              
        
    }//GEN-LAST:event_roadsubmitbuttonActionPerformed

    private void roadupdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roadupdatebuttonActionPerformed
        total();
        try {
             if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
            }
       
        String name=SelectsiteRoad.getSelectedItem().toString();
        String tablename=name+"road";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "UPDATE "+tablename
        +" SET Date=?,Name=?,TotalRoad=?, Excavation=?, Dressing=?, Wbmlayer1=?, Wbmlayer2=?, Wbmlayer3=?,Wbmlayer4=?, Wbmlayer5=?, WaterBOunding=?, FinalTouch=?, TotalAmount=? WHERE ID=?";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
    //System.out.println(sql);
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) dateroadfield.getDateEditor().getUiComponent()).getText());
pst.setString(2,namefieldRoad.getText());
pst.setInt(3,Integer.parseInt(totalroadfield.getText()));
pst.setFloat(4,excavation);
pst.setFloat(5,dressing);
pst.setFloat(6,wbmlayer1);
pst.setFloat(7,wbmlayer2);
pst.setFloat(8,wbmlayer3);
pst.setFloat(9,wbmlayer4);
pst.setFloat(10,wbmlayer5);
pst.setFloat(11,waterBOunding);
pst.setFloat(12,FinalTouch);
pst.setFloat(13,totalamount);
pst.setInt(14,id);
pst.executeUpdate();
st.showTableData(tableroad, SelectsiteRoad, "road");
refresh();
id=0;
return;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_roadupdatebuttonActionPerformed

    private void backroadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backroadbuttonActionPerformed
         new WorkDone().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backroadbuttonActionPerformed

    private void finaltouchroadfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finaltouchroadfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finaltouchroadfieldActionPerformed

    private void dressignroadfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dressignroadfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dressignroadfieldActionPerformed

    private void waterboundingfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterboundingfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterboundingfieldActionPerformed

    private void tableroadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroadMouseClicked
        int i=tableroad.getSelectedRow();
        TableModel model=tableroad.getModel();
        id=Integer.parseInt(model.getValueAt(i,0).toString());
         String date=model.getValueAt(i,1).toString();
         namefieldRoad.setText(model.getValueAt(i,2).toString());
         totalroadfield.setText(model.getValueAt(i,3).toString());
         ((JTextField) dateroadfield.getDateEditor().getUiComponent()).setText(date);
       
   
    }//GEN-LAST:event_tableroadMouseClicked

    private void SelectsiteRoadPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_SelectsiteRoadPopupMenuWillBecomeInvisible
        st.FillTableUSingcombo(SelectsiteRoad, tableroad, "road");
    }//GEN-LAST:event_SelectsiteRoadPopupMenuWillBecomeInvisible

    private void totalroadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalroadfieldKeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    } 
    }//GEN-LAST:event_totalroadfieldKeyTyped

    private void excavationroadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_excavationroadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_excavationroadfieldKeyTyped

    private void contadharfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadharfield1KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contadharfield1KeyTyped

    private void dressignroadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dressignroadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}       // TODO add your handling code here:
    }//GEN-LAST:event_dressignroadfieldKeyTyped

    private void contaddressfield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contaddressfield2KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield2KeyTyped

    private void wbm1roadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wbm1roadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}
// TODO add your handling code here:
    }//GEN-LAST:event_wbm1roadfieldKeyTyped

    private void contmobilefield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contmobilefield2KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}       // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield2KeyTyped

    private void wbm2roadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wbm2roadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_wbm2roadfieldKeyTyped

    private void contsalaryfield6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfield6KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield6KeyTyped

    private void wbm3roadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wbm3roadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_wbm3roadfieldKeyTyped

    private void contaddressfield3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contaddressfield3KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield3KeyTyped

    private void wbm4roadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wbm4roadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_wbm4roadfieldKeyTyped

    private void contmobilefield3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contmobilefield3KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield3KeyTyped

    private void wbmroadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wbmroadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_wbmroadfieldKeyTyped

    private void contsalaryfield5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfield5KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }         // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield5KeyTyped

    private void waterboundingfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_waterboundingfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_waterboundingfieldKeyTyped

    private void contsalaryfield8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfield8KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield8KeyTyped

    private void finaltouchroadfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finaltouchroadfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_finaltouchroadfieldKeyTyped

    private void contsalaryfield7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfield7KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield7KeyTyped

    private void wbm4roadfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wbm4roadfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wbm4roadfieldActionPerformed

    private void contsalaryfield5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contsalaryfield5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield5ActionPerformed

    private void excavationroadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_excavationroadfieldFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_excavationroadfieldFocusLost

    private void contadharfield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contadharfield1FocusLost
      count=0;  // TODO add your handling code here:
    }//GEN-LAST:event_contadharfield1FocusLost

    private void dressignroadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dressignroadfieldFocusLost
       count=0;  // TODO add your handling code here:
    }//GEN-LAST:event_dressignroadfieldFocusLost

    private void contaddressfield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaddressfield2FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield2FocusLost

    private void wbm1roadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wbm1roadfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_wbm1roadfieldFocusLost

    private void contmobilefield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contmobilefield2FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield2FocusLost

    private void wbm2roadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wbm2roadfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_wbm2roadfieldFocusLost

    private void contsalaryfield6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contsalaryfield6FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield6FocusLost

    private void wbm3roadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wbm3roadfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_wbm3roadfieldFocusLost

    private void contaddressfield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaddressfield3FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield3FocusLost

    private void wbm4roadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wbm4roadfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_wbm4roadfieldFocusLost

    private void contmobilefield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contmobilefield3FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield3FocusLost

    private void wbmroadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wbmroadfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_wbmroadfieldFocusLost

    private void contsalaryfield5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contsalaryfield5FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield5FocusLost

    private void waterboundingfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_waterboundingfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_waterboundingfieldFocusLost

    private void contsalaryfield8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contsalaryfield8FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield8FocusLost

    private void finaltouchroadfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finaltouchroadfieldFocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_finaltouchroadfieldFocusLost

    private void contsalaryfield7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contsalaryfield7FocusLost
 count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield7FocusLost

    /**
     * @param args the command line arguments
     */
 
   private void remian(){
try{
   if(SelectsiteRoad.getSelectedItem()!=null){
        String name=SelectsiteRoad.getSelectedItem().toString();
        String tablename=name+"road";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT TotalAmount FROM "+tablename+" ORDER BY ID DESC LIMIT 1";
    System.out.println(sql);
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
total=rs.getInt(1);
 System.out.println(total);
//System.out.println(remaining);
}}}
   else{
   return;
   }

}
catch(Exception ex){
    System.out.println("mai chal tha");
    total=0;
//JOptionPane.showMessageDialog(null, ex);
 
}


}
        
   
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RoadForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RoadForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
 

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectsiteRoad;
    private javax.swing.JLabel Shuttringtower;
    private javax.swing.JButton backroadbutton;
    private javax.swing.JLabel barbindtower;
    private javax.swing.JLabel completetower;
    private javax.swing.JTextField contaddressfield2;
    private javax.swing.JTextField contaddressfield3;
    private javax.swing.JTextField contadharfield1;
    private javax.swing.JTextField contmobilefield2;
    private javax.swing.JTextField contmobilefield3;
    private javax.swing.JTextField contsalaryfield5;
    private javax.swing.JTextField contsalaryfield6;
    private javax.swing.JTextField contsalaryfield7;
    private javax.swing.JTextField contsalaryfield8;
    private com.toedter.calendar.JDateChooser dateroadfield;
    private javax.swing.JLabel datetowerlabel;
    private javax.swing.JTextField dressignroadfield;
    private javax.swing.JTextField excavationroadfield;
    private javax.swing.JLabel excavationtower;
    private javax.swing.JTextField finaltouchroadfield;
    private javax.swing.JLabel headingroad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelboltingfirst;
    private javax.swing.JLabel labelfinal;
    private javax.swing.JLabel labelfinal1;
    private javax.swing.JLabel labelfinal2;
    private javax.swing.JLabel labelraft;
    private javax.swing.JTextField namefieldRoad;
    private javax.swing.JLabel pcctower;
    private javax.swing.JButton roaddelbuttton;
    private javax.swing.JButton roadsubmitbutton;
    private javax.swing.JButton roadupdatebutton;
    private javax.swing.JTable tableroad;
    private javax.swing.JTextField totalroadfield;
    private javax.swing.JLabel totaltower;
    private javax.swing.JTextField waterboundingfield;
    private javax.swing.JTextField wbm1roadfield;
    private javax.swing.JTextField wbm2roadfield;
    private javax.swing.JTextField wbm3roadfield;
    private javax.swing.JTextField wbm4roadfield;
    private javax.swing.JTextField wbmroadfield;
    // End of variables declaration//GEN-END:variables
}
