
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class TowerForm extends javax.swing.JFrame {
    int id=0;
    showTable st=new showTable();
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst = null;
    float excavation;
    float pcc;
   float bar;
  float shuttring;
    float raft;
    float Boltleftfield;
    float Boltfinal;
    float size1;
    float totalamount;
    int count=0;
    float total;
    
    
    void total(){
         excavation =Float.parseFloat(excavatowerfield.getText())*Float.parseFloat(contadharfield1.getText());
         pcc =Float.parseFloat(pcctowerfield.getText())*Float.parseFloat(contaddressfield2.getText());
         bar =Float.parseFloat(bartowerfield.getText())*Float.parseFloat(contmobilefield2.getText());
         shuttring =Float.parseFloat(shuttringtowerfiled.getText())*Float.parseFloat(contsalaryfield6.getText());
         raft =Float.parseFloat(rafttowerfiield.getText())*Float.parseFloat(contaddressfield3.getText());
         Boltleftfield =Float.parseFloat(Boltleft.getText())*Float.parseFloat(contmobilefield3.getText());
         Boltfinal =Float.parseFloat(boltingfinaltower.getText())*Float.parseFloat(contsalaryfield5.getText());
          size1 =Float.parseFloat(ltextfieldtower.getText())*Float.parseFloat(btowerfield.getText())*Float.parseFloat(htowerfield.getText());
         totalamount=excavation+pcc+bar+shuttring+raft+Boltleftfield+Boltfinal;
    }
   
    /**
     * Creates new form TowerForm
     */
    public TowerForm() {
       
        initComponents();
        ShowdropDown();
        showTableData();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        completetower = new javax.swing.JLabel();
        complete = new javax.swing.JTextField();
        bartowerfield = new javax.swing.JTextField();
        shuttringtowerfiled = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        towerdelbuttton = new javax.swing.JButton();
        excavatowerfield = new javax.swing.JTextField();
        excavationtower = new javax.swing.JLabel();
        towersubmitbutton = new javax.swing.JButton();
        barbindtower = new javax.swing.JLabel();
        Shuttringtower = new javax.swing.JLabel();
        pcctowerfield = new javax.swing.JTextField();
        totaltower = new javax.swing.JLabel();
        pcctower = new javax.swing.JLabel();
        texttotaltower = new javax.swing.JTextField();
        backtowerbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletower = new javax.swing.JTable();
        labelboltingfirst = new javax.swing.JLabel();
        labelfinal = new javax.swing.JLabel();
        rafttowerfiield = new javax.swing.JTextField();
        Boltleft = new javax.swing.JTextField();
        labelraft = new javax.swing.JLabel();
        boltingfinaltower = new javax.swing.JTextField();
        ltextfieldtower = new javax.swing.JTextField();
        size = new javax.swing.JLabel();
        btowerfield = new javax.swing.JTextField();
        htowerfield = new javax.swing.JTextField();
        contsalaryfield5 = new javax.swing.JTextField();
        contadharfield1 = new javax.swing.JTextField();
        contaddressfield2 = new javax.swing.JTextField();
        contmobilefield2 = new javax.swing.JTextField();
        contaddressfield3 = new javax.swing.JTextField();
        contsalaryfield6 = new javax.swing.JTextField();
        contmobilefield3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combosite = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datetowerfield = new com.toedter.calendar.JDateChooser();
        datetowerlabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Account No", "Adhar No", "Address", "Mobile No", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        completetower.setText("Complete");

        complete.setText("0");
        complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeActionPerformed(evt);
            }
        });
        complete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                completeKeyTyped(evt);
            }
        });

        bartowerfield.setText("0");
        bartowerfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bartowerfieldFocusLost(evt);
            }
        });
        bartowerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bartowerfieldActionPerformed(evt);
            }
        });
        bartowerfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bartowerfieldKeyTyped(evt);
            }
        });

        shuttringtowerfiled.setText("0");
        shuttringtowerfiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                shuttringtowerfiledFocusLost(evt);
            }
        });
        shuttringtowerfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuttringtowerfiledActionPerformed(evt);
            }
        });
        shuttringtowerfiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                shuttringtowerfiledKeyTyped(evt);
            }
        });

        jLabel1.setText("Add Towers Details");

        towerdelbuttton.setText("Delete");
        towerdelbuttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                towerdelbutttonActionPerformed(evt);
            }
        });

        excavatowerfield.setText("0");
        excavatowerfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                excavatowerfieldFocusLost(evt);
            }
        });
        excavatowerfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                excavatowerfieldKeyTyped(evt);
            }
        });

        excavationtower.setText("Excavation");

        towersubmitbutton.setText("Submit");
        towersubmitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                towersubmitbuttonActionPerformed(evt);
            }
        });

        barbindtower.setText("Bar Binding");

        Shuttringtower.setText("Shuttring");

        pcctowerfield.setText("0");
        pcctowerfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pcctowerfieldFocusLost(evt);
            }
        });
        pcctowerfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pcctowerfieldKeyTyped(evt);
            }
        });

        totaltower.setText("Total Tower  ");

        pcctower.setText("Pcc");

        texttotaltower.setText("0");
        texttotaltower.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texttotaltowerKeyTyped(evt);
            }
        });

        backtowerbutton.setText("Back");
        backtowerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtowerbuttonActionPerformed(evt);
            }
        });

        tabletower.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Total Tower", "Complete", "Pcc", "Excavation", "Pcc", "Bar Binding", "Shuttring", "Raft", "Bolting First", "Bolting Final", "Size", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabletower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletowerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabletower);

        labelboltingfirst.setText("Bolting First Left");

        labelfinal.setText("Bolting Final Left");

        rafttowerfiield.setText("0");
        rafttowerfiield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rafttowerfiieldFocusLost(evt);
            }
        });
        rafttowerfiield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rafttowerfiieldKeyTyped(evt);
            }
        });

        Boltleft.setText("0");
        Boltleft.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BoltleftFocusLost(evt);
            }
        });
        Boltleft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BoltleftKeyTyped(evt);
            }
        });

        labelraft.setText("Raft");

        boltingfinaltower.setText("0");
        boltingfinaltower.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                boltingfinaltowerFocusLost(evt);
            }
        });
        boltingfinaltower.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boltingfinaltowerKeyTyped(evt);
            }
        });

        ltextfieldtower.setText("0");
        ltextfieldtower.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ltextfieldtowerFocusLost(evt);
            }
        });
        ltextfieldtower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltextfieldtowerActionPerformed(evt);
            }
        });
        ltextfieldtower.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ltextfieldtowerKeyTyped(evt);
            }
        });

        size.setText("Size");

        btowerfield.setText("0");
        btowerfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btowerfieldFocusLost(evt);
            }
        });
        btowerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btowerfieldActionPerformed(evt);
            }
        });
        btowerfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btowerfieldKeyTyped(evt);
            }
        });

        htowerfield.setText("0");
        htowerfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                htowerfieldFocusLost(evt);
            }
        });
        htowerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htowerfieldActionPerformed(evt);
            }
        });
        htowerfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                htowerfieldKeyTyped(evt);
            }
        });

        contsalaryfield5.setText("0");
        contsalaryfield5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contsalaryfield5FocusLost(evt);
            }
        });
        contsalaryfield5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfield5KeyTyped(evt);
            }
        });

        contadharfield1.setText("0");
        contadharfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contadharfield1FocusLost(evt);
            }
        });
        contadharfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contadharfield1KeyTyped(evt);
            }
        });

        contaddressfield2.setText("0");
        contaddressfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contaddressfield2FocusLost(evt);
            }
        });
        contaddressfield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contaddressfield2KeyTyped(evt);
            }
        });

        contmobilefield2.setText("0");
        contmobilefield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contmobilefield2FocusLost(evt);
            }
        });
        contmobilefield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contmobilefield2ActionPerformed(evt);
            }
        });
        contmobilefield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contmobilefield2KeyTyped(evt);
            }
        });

        contaddressfield3.setText("0");
        contaddressfield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contaddressfield3FocusLost(evt);
            }
        });
        contaddressfield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contaddressfield3KeyTyped(evt);
            }
        });

        contsalaryfield6.setText("0");
        contsalaryfield6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contsalaryfield6FocusLost(evt);
            }
        });
        contsalaryfield6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contsalaryfield6KeyTyped(evt);
            }
        });

        contmobilefield3.setText("0");
        contmobilefield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contmobilefield3FocusLost(evt);
            }
        });
        contmobilefield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contmobilefield3KeyTyped(evt);
            }
        });

        jLabel2.setText("Select Site");

        combosite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combositePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                combositePopupMenuWillBecomeVisible(evt);
            }
        });
        combosite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combositeMouseClicked(evt);
            }
        });
        combosite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combositeActionPerformed(evt);
            }
        });

        jLabel3.setText("Rate");

        jLabel4.setText("L");

        jLabel5.setText("W");

        jLabel6.setText("H");

        datetowerlabel.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelboltingfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelraft, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfinal)
                            .addComponent(datetowerlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texttotaltower, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boltleft, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rafttowerfiield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shuttringtowerfiled, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bartowerfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pcctowerfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excavatowerfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(complete)
                            .addComponent(boltingfinaltower)
                            .addComponent(datetowerfield, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(contmobilefield2)
                                .addComponent(contaddressfield2)
                                .addComponent(contadharfield1)
                                .addComponent(contsalaryfield6)
                                .addComponent(contaddressfield3)
                                .addComponent(contmobilefield3)
                                .addComponent(contsalaryfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ltextfieldtower, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(htowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combosite, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(barbindtower, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcctower, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Shuttringtower, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(excavationtower, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(completetower, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totaltower)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backtowerbutton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(towersubmitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(towerdelbuttton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combosite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datetowerlabel)
                            .addComponent(datetowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totaltower)
                            .addComponent(texttotaltower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(complete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(completetower))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(excavatowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(excavationtower))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcctower)
                                    .addComponent(pcctowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barbindtower)
                                    .addComponent(bartowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shuttringtowerfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Shuttringtower, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelraft)
                                    .addComponent(rafttowerfiield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelboltingfirst)
                                    .addComponent(Boltleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boltingfinaltower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(contadharfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contaddressfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contmobilefield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(contsalaryfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(contaddressfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contmobilefield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contsalaryfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltextfieldtower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(htowerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(towersubmitbutton)
                    .addComponent(towerdelbuttton))
                .addGap(18, 18, 18)
                .addComponent(backtowerbutton)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void towerdelbutttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_towerdelbutttonActionPerformed
          try {
               if(id==0){
                JOptionPane.showMessageDialog(null, "Please select The Field From Table First");
                return;
            }
       
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"tower";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "DELETE FROM "+tablename+" WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
            pst = con.prepareStatement(sql);
            pst.setInt(1,id);
            pst.executeUpdate();
            showTableData();
            JOptionPane.showMessageDialog(null, "delete successfully");
refresh();
id=0;
return ;
}

}
        } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(null,  "please enter all the details or fill it correctly");
    }
    }//GEN-LAST:event_towerdelbutttonActionPerformed

    private void towersubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_towersubmitbuttonActionPerformed

                try {
                    
                    
                    if(((JTextField) datetowerfield.getDateEditor().getUiComponent()).getText().length()==0){
             JOptionPane.showMessageDialog(null, "Date Can not be empty");
             return;
            }
                   
                   
                    total();
                     remian();

                     float New_total=total+totalamount;
                     //System.out.print(New_total);
                     
       
        String name=combosite.getSelectedItem().toString();
        
        String tablename=name+"tower";
        con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
        

rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "INSERT INTO "+tablename
        +"(Date, TotalTower, Complete, Excavation, Pcc, BarBinding, Shuttring,Raft,BoltingFirst,BoltingFinal,Size,TotalAmount)"
+"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) datetowerfield.getDateEditor().getUiComponent()).getText());
pst.setInt(2,Integer.parseInt(texttotaltower.getText()));
pst.setInt(3,Integer.parseInt(complete.getText()));
pst.setFloat(4,excavation);
pst.setFloat(5,pcc);
pst.setFloat(6,bar);
pst.setFloat(7,shuttring);
pst.setFloat(8,raft);
pst.setFloat(9,Boltleftfield);
pst.setFloat(10,Boltfinal);

pst.setFloat(11,size1);
pst.setFloat(12,New_total);

pst.executeUpdate();
showTableData();
refresh();
return ;
}

} 
  //System.out.println("chal bc");
String sql1="CREATE TABLE "+ tablename +
                "("+" ID INT NOT NULL AUTO_INCREMENT, Date TEXT(20), TotalTower INT(25),Complete INT(10),Excavation FLOAT(15),Pcc FLOAT(15),BarBinding FLOAT(10),Shuttring FLOAT(30),Raft FLOAT(30),BoltingFirst FLOAT(30),BoltingFinal FLOAT(30),Size FLOAT(30),TotalAmount FLOAT(30),PRIMARY KEY(ID))";
//System.out.println(sql1);
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql1);

pst.executeUpdate(sql1);
String sql = "INSERT INTO "+tablename
        +"(Date, TotalTower, Complete, Excavation, Pcc, BarBinding, Shuttring,Raft,BoltingFirst,BoltingFinal,Size,TotalAmount)"
+"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
pst = con.prepareStatement(sql);
pst.setString(1,((JTextField) datetowerfield.getDateEditor().getUiComponent()).getText());
pst.setInt(2,Integer.parseInt(texttotaltower.getText()));
pst.setInt(3,Integer.parseInt(complete.getText()));
pst.setFloat(4,excavation);
pst.setFloat(5,pcc);
pst.setFloat(6,bar);
pst.setFloat(7,shuttring);
pst.setFloat(8,raft);
pst.setFloat(9,Boltleftfield);
pst.setFloat(10,Boltfinal);

pst.setFloat(11,size1);
pst.setFloat(12,New_total);
pst.executeUpdate();
showTableData();
refresh();


       
        
        
    } catch (SQLException ex) {
       
        Logger.getLogger(NewcontractorForm.class.getName()).log(Level.SEVERE, null, ex);
    }
              
    }//GEN-LAST:event_towersubmitbuttonActionPerformed
private void refresh(){
//datetowerfield.setDateFormatString("");
texttotaltower.setText("0");
complete.setText("0");
excavatowerfield.setText("0");
contadharfield1.setText("0");
pcctowerfield.setText("0");
contaddressfield2.setText("0");
bartowerfield.setText("0");
contmobilefield2.setText("0");
shuttringtowerfiled.setText("0");
contsalaryfield6.setText("0");
rafttowerfiield.setText("0");
contaddressfield3.setText("0");
Boltleft.setText("0");
contmobilefield3.setText("0");
boltingfinaltower.setText("0");
contsalaryfield5.setText("0");
ltextfieldtower.setText("0");
btowerfield.setText("0");
htowerfield.setText("0");




}
    private void backtowerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtowerbuttonActionPerformed
        new WorkDone().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backtowerbuttonActionPerformed

    private void btowerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btowerfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btowerfieldActionPerformed

    private void combositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combositeActionPerformed
       
        
    }//GEN-LAST:event_combositeActionPerformed

    private void ltextfieldtowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltextfieldtowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ltextfieldtowerActionPerformed

    private void tabletowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletowerMouseClicked
            
         int i=tabletower.getSelectedRow();
        TableModel model=tabletower.getModel();
        id= Integer.parseInt(model.getValueAt(i,0).toString());
         String date=model.getValueAt(i,1).toString();
         texttotaltower.setText(model.getValueAt(i,2).toString());
         complete.setText(model.getValueAt(i,3).toString());
         ((JTextField) datetowerfield.getDateEditor().getUiComponent()).setText(date);
       
   
    }//GEN-LAST:event_tabletowerMouseClicked

    private void combositeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combositeMouseClicked
        
    }//GEN-LAST:event_combositeMouseClicked

    private void combositePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combositePopupMenuWillBecomeVisible
        
    }//GEN-LAST:event_combositePopupMenuWillBecomeVisible

    private void combositePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combositePopupMenuWillBecomeInvisible
        
        st.FillTableUSingcombo(combosite, tabletower, "tower");
 
    }//GEN-LAST:event_combositePopupMenuWillBecomeInvisible

    private void completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completeActionPerformed

    private void contmobilefield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contmobilefield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield2ActionPerformed

    private void bartowerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bartowerfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bartowerfieldActionPerformed

    private void shuttringtowerfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuttringtowerfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shuttringtowerfiledActionPerformed

    private void htowerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htowerfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htowerfieldActionPerformed

    private void texttotaltowerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texttotaltowerKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    } 
    }//GEN-LAST:event_texttotaltowerKeyTyped

    private void completeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_completeKeyTyped
      char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }  
    }//GEN-LAST:event_completeKeyTyped

    private void excavatowerfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_excavatowerfieldKeyTyped
     char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
}
    }//GEN-LAST:event_excavatowerfieldKeyTyped

    private void contadharfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadharfield1KeyTyped
       char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
}

    }//GEN-LAST:event_contadharfield1KeyTyped

    private void pcctowerfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcctowerfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
}        // TODO add your handling code here:
    }//GEN-LAST:event_pcctowerfieldKeyTyped

    private void contaddressfield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contaddressfield2KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield2KeyTyped

    private void bartowerfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bartowerfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_bartowerfieldKeyTyped

    private void contmobilefield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contmobilefield2KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}       // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield2KeyTyped

    private void shuttringtowerfiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shuttringtowerfiledKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_shuttringtowerfiledKeyTyped

    private void contsalaryfield6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfield6KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}    // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield6KeyTyped

    private void rafttowerfiieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rafttowerfiieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_rafttowerfiieldKeyTyped

    private void contaddressfield3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contaddressfield3KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield3KeyTyped

    private void BoltleftKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BoltleftKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_BoltleftKeyTyped

    private void contmobilefield3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contmobilefield3KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield3KeyTyped

    private void boltingfinaltowerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boltingfinaltowerKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_boltingfinaltowerKeyTyped

    private void contsalaryfield5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contsalaryfield5KeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield5KeyTyped

    private void ltextfieldtowerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ltextfieldtowerKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}     // TODO add your handling code here:
    }//GEN-LAST:event_ltextfieldtowerKeyTyped

    private void btowerfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btowerfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btowerfieldKeyTyped

    private void htowerfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_htowerfieldKeyTyped
char input=evt.getKeyChar();
       
    if((input<'0'|| input >'9') && input!= '\b' && input!='.'){
        JOptionPane.showMessageDialog(null,"Only Numbers");
    evt.consume();
    }
if(input=='.'){
count++;}
if(count>1){
    System.out.println();
    evt.consume();
    count--;
//JOptionPane.showMessageDialog(null,"Two Decimals are not allow");
}         // TODO add your handling code here:
    }//GEN-LAST:event_htowerfieldKeyTyped

    private void contadharfield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contadharfield1FocusLost
count=0;        
    }//GEN-LAST:event_contadharfield1FocusLost

    private void contaddressfield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaddressfield2FocusLost
    count=0;     // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield2FocusLost

    private void contmobilefield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contmobilefield2FocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield2FocusLost

    private void contsalaryfield6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contsalaryfield6FocusLost
count=0;       // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield6FocusLost

    private void contaddressfield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaddressfield3FocusLost
count=0;       // TODO add your handling code here:
    }//GEN-LAST:event_contaddressfield3FocusLost

    private void contmobilefield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contmobilefield3FocusLost
count=0;       // TODO add your handling code here:
    }//GEN-LAST:event_contmobilefield3FocusLost

    private void contsalaryfield5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contsalaryfield5FocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_contsalaryfield5FocusLost

    private void ltextfieldtowerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ltextfieldtowerFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_ltextfieldtowerFocusLost

    private void btowerfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btowerfieldFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_btowerfieldFocusLost

    private void htowerfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_htowerfieldFocusLost
count=0;          // TODO add your handling code here:
    }//GEN-LAST:event_htowerfieldFocusLost

    private void excavatowerfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_excavatowerfieldFocusLost
        count=0;
    }//GEN-LAST:event_excavatowerfieldFocusLost

    private void pcctowerfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcctowerfieldFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_pcctowerfieldFocusLost

    private void bartowerfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bartowerfieldFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_bartowerfieldFocusLost

    private void shuttringtowerfiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_shuttringtowerfiledFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_shuttringtowerfiledFocusLost

    private void rafttowerfiieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rafttowerfiieldFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_rafttowerfiieldFocusLost

    private void BoltleftFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoltleftFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_BoltleftFocusLost

    private void boltingfinaltowerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boltingfinaltowerFocusLost
count=0;        // TODO add your handling code here:
    }//GEN-LAST:event_boltingfinaltowerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equalsIgnoreCase(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TowerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TowerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TowerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TowerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TowerForm().setVisible(true);
            }
        });
    }
    public void ShowdropDown(){
        //combosite.removeAllItems();
        try{
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM site";
pst = con.prepareStatement(sql);
rs=pst.executeQuery(sql);
while((rs.next())){
    String name=rs.getString("sitename");
combosite.addItem(name);
}
 }catch(Exception ex){
     JOptionPane.showMessageDialog(null, ex);
     
 }
    }
      public void showTableData(){
          
try{
    String name=combosite.getSelectedItem().toString();
        String tablename=name+"tower";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
String sql = "SELECT * FROM "+tablename;
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
tabletower.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception ex){

 
}
 
}
      private void remian(){
try{
   if(combosite.getSelectedItem()!=null){
        String name=combosite.getSelectedItem().toString();
        String tablename=name+"tower";
con = DriverManager.getConnection("jdbc:mysql://localhost/user","root","root");
rs=con.getMetaData().getTables(null, null, null, null);
while(rs.next()){
    String check=rs.getString("Table_Name");
if(check!=null &&check.equalsIgnoreCase(tablename)){
String sql = "SELECT TotalAmount FROM "+tablename+" ORDER BY ID DESC LIMIT 1";
    System.out.println(sql);
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
rs.next();
total=rs.getInt(1);
 System.out.println(total);
//System.out.println(remaining);
}}}
   else{
   return;
   }

}
catch(Exception ex){
    System.out.println("mai chal tha");
    total=0;
//JOptionPane.showMessageDialog(null, ex);
 
}


}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Boltleft;
    private javax.swing.JLabel Shuttringtower;
    private javax.swing.JButton backtowerbutton;
    private javax.swing.JLabel barbindtower;
    private javax.swing.JTextField bartowerfield;
    private javax.swing.JTextField boltingfinaltower;
    private javax.swing.JTextField btowerfield;
    private javax.swing.JComboBox<String> combosite;
    private javax.swing.JTextField complete;
    private javax.swing.JLabel completetower;
    private javax.swing.JTextField contaddressfield2;
    private javax.swing.JTextField contaddressfield3;
    private javax.swing.JTextField contadharfield1;
    private javax.swing.JTextField contmobilefield2;
    private javax.swing.JTextField contmobilefield3;
    private javax.swing.JTextField contsalaryfield5;
    private javax.swing.JTextField contsalaryfield6;
    private com.toedter.calendar.JDateChooser datetowerfield;
    private javax.swing.JLabel datetowerlabel;
    private javax.swing.JLabel excavationtower;
    private javax.swing.JTextField excavatowerfield;
    private javax.swing.JTextField htowerfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelboltingfirst;
    private javax.swing.JLabel labelfinal;
    private javax.swing.JLabel labelraft;
    private javax.swing.JTextField ltextfieldtower;
    private javax.swing.JLabel pcctower;
    private javax.swing.JTextField pcctowerfield;
    private javax.swing.JTextField rafttowerfiield;
    private javax.swing.JTextField shuttringtowerfiled;
    private javax.swing.JLabel size;
    private javax.swing.JTable tabletower;
    private javax.swing.JTextField texttotaltower;
    private javax.swing.JLabel totaltower;
    private javax.swing.JButton towerdelbuttton;
    private javax.swing.JButton towersubmitbutton;
    // End of variables declaration//GEN-END:variables
}
