
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author piyush veerbhan
 */
public class WorkDone extends javax.swing.JFrame {

    /**
     * Creates new form WorkDone
     */
    public WorkDone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnroad = new javax.swing.JButton();
        btntower = new javax.swing.JButton();
        btncable = new javax.swing.JButton();
        btndrain = new javax.swing.JButton();
        btnequipment = new javax.swing.JButton();
        btnallsitegrowel = new javax.swing.JButton();
        btnothers = new javax.swing.JButton();
        btnallsitepcc = new javax.swing.JButton();
        btnearthing = new javax.swing.JButton();
        btnbckwork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnroad.setText("Road Construction");
        btnroad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroadActionPerformed(evt);
            }
        });

        btntower.setText("Tower");
        btntower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntowerActionPerformed(evt);
            }
        });

        btncable.setText("Cable Tracing");
        btncable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncableActionPerformed(evt);
            }
        });

        btndrain.setText("Drain");
        btndrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrainActionPerformed(evt);
            }
        });

        btnequipment.setText("Equipments");
        btnequipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequipmentActionPerformed(evt);
            }
        });

        btnallsitegrowel.setText("All site Growel");
        btnallsitegrowel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallsitegrowelActionPerformed(evt);
            }
        });

        btnothers.setText("Others");
        btnothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnothersActionPerformed(evt);
            }
        });

        btnallsitepcc.setText("All Site PCC");
        btnallsitepcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallsitepccActionPerformed(evt);
            }
        });

        btnearthing.setText("Earthing");
        btnearthing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnearthingActionPerformed(evt);
            }
        });

        btnbckwork.setText("Back");
        btnbckwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbckworkActionPerformed(evt);
            }
        });

        jLabel1.setText("Work Done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnallsitepcc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnallsitegrowel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnearthing, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnothers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnequipment, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncable, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntower, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnroad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndrain, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnbckwork, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(btntower, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnroad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnequipment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndrain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnearthing, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnallsitepcc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnallsitegrowel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnothers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnbckwork, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroadActionPerformed
        try {
            new RoadForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(WorkDone.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_btnroadActionPerformed

    private void btntowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntowerActionPerformed
        new TowerForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntowerActionPerformed

    private void btncableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncableActionPerformed
        new CableTracingFrom().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncableActionPerformed

    private void btndrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrainActionPerformed
        new Drain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btndrainActionPerformed

    private void btnequipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequipmentActionPerformed
       new EquipmentForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnequipmentActionPerformed

    private void btnallsitegrowelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallsitegrowelActionPerformed
        new Growel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnallsitegrowelActionPerformed

    private void btnothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnothersActionPerformed
      new otherForm().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnothersActionPerformed

    private void btnallsitepccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallsitepccActionPerformed
        new PccAllSite().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnallsitepccActionPerformed

    private void btnearthingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnearthingActionPerformed
        new EartingForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnearthingActionPerformed

    private void btnbckworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbckworkActionPerformed
        new viewSiteform().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbckworkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkDone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkDone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkDone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkDone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkDone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnallsitegrowel;
    private javax.swing.JButton btnallsitepcc;
    private javax.swing.JButton btnbckwork;
    private javax.swing.JButton btncable;
    private javax.swing.JButton btndrain;
    private javax.swing.JButton btnearthing;
    private javax.swing.JButton btnequipment;
    private javax.swing.JButton btnothers;
    private javax.swing.JButton btnroad;
    private javax.swing.JButton btntower;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
